### ISSUE TITLE
Option to display total size of directory

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#313] opened 2020-03-27 00:35 UTC
Is it possible to have an option to display the total size of a directory and its contents, i.e. the output of

    du -sh <dir_path> | awk '{print $1}'

in the bottom left corner (between the permissions and the time infos), instead of the size of the directory file itself?

**Comment by shabahengam** [comment] 2020-03-27 17:12
Is this not a duplicate of #310 ?

**Comment by n0ibe** [comment] 2020-03-27 17:46
Oops, it is.

**Closed** 2020-04-01 15:09 UTC
Labels: duplicate
