### ISSUE TITLE
[BUG] Question Marks trying to enable icons

### ISSUE THREAD

**Issue by madrigal1** [gokcehan/lf#1159] opened 2023-03-15 17:18 UTC
### Discussed in https://github.com/gokcehan/lf/discussions/1158

<div type='discussions-op-text'>

<sup>Originally posted by **madrigal1** March 15, 2023</sup>
![image](https://user-images.githubusercontent.com/30615210/225389226-d03781dd-9dcb-4d69-ac5a-dbd6e2ae6a8a.png)
icons file is the icons.example
set icons true is added in lfrc</div>

**Comment by gokcehan** [comment] 2023-03-15 17:34
@madrigal1 There is no such thing as `set icons true`. See #758 for more information.

Do you have nerd fonts installed?

**Comment by madrigal1** [comment] 2023-03-16 04:20
Ah a lot of new lf users come from popular youtubers which use the old commands and outdated syntax like the use icons true and using env variables to set the colors and icons thanks for clearing that up

**Comment by madrigal1** [comment] 2023-03-16 04:21
Yes i have nerd fonts installed

**Comment by madrigal1** [comment] 2023-03-16 05:16
using the new documentation still doesn't fix the issue :
![image](https://user-images.githubusercontent.com/30615210/225521463-cc2c41f5-ea53-46a9-a28a-a6d08fe9436f.png)

**Comment by madrigal1** [comment] 2023-03-16 05:17
still no icons :
![image](https://user-images.githubusercontent.com/30615210/225521542-d2aaf1b9-99a7-4374-99f4-58c724c4493e.png)

to confirm i only need to add the icons file in the ~/config/lf/icons right ?
no additional command to be added in the lfrc ?

**Comment by madrigal1** [comment] 2023-03-16 05:19
@gokcehan any idea as to what i am missing ?

**Comment by madrigal1** [comment] 2023-03-16 05:24
```
set icons
set icons true
set icons on
<not including this in lfrc>
```
none of the above combinations work

**Comment by madrigal1** [comment] 2023-03-16 05:27
i have also added lf_icons env var as fallback:
![image](https://user-images.githubusercontent.com/30615210/225522981-a699f3e7-2471-4c44-bae7-bf68edc3c91e.png)

**Comment by gokcehan** [comment] 2023-03-16 11:23
@madrigal1 You are right, you also need `set icons` in your lfrc file. I have now updated the wiki page accordingly.

Your latest screenshots do not seem to have `set icons` so I'm not sure what can be the problem this time.

**Comment by joelim-work** [comment] 2023-03-17 02:56
There seems to be more than one issue here:

- Enabling icons (they are disabled by default)
- Displaying Nerd Fonts characters when icons are enabled

I think this would be easier to diagnose if you are able to reproduce from scratch, could you please try the following?

1. Mention what version of `lf` you are using (or even better obtain the latest version by building from source)
2. Backup then delete all your `lf`-related config
3. Create an lfrc file containing nothing but `set icons` to enable the icons (as a side note you can also type `:set icons`/`:set noicons` in the command line to enable/disable icons while `lf` is running)
4. Create an icons file containing nothing but `fi ` to ensure that Nerd Fonts icons work

I have never seen question marks as icons before - normally I would associate that with the terminal not being able to find or load the font, but that doesn't seem to be the case here. Also you wouldn't happen to be using a dotfile configuration manager and your config files just simply aren't synced?

**Comment by madrigal1** [comment] 2023-03-17 03:56
Thanks @joelim-work for the response.
* changed lfrc to only set icons
![image](https://user-images.githubusercontent.com/30615210/225808619-60e915ca-4ff9-45ee-b830-1efa9bae4b8c.png)

* changed icons to only include fi
![image](https://user-images.githubusercontent.com/30615210/225808826-d9948fc2-5ff6-4239-a0a6-7a4b0a102a7a.png)

*lf version
![image](https://user-images.githubusercontent.com/30615210/225808990-a6d776b8-31fa-4667-a785-8589ab0d2120.png)

let me know if i can provide any additional info

**Comment by joelim-work** [comment] 2023-03-17 05:21
OK so it looks like the `set icons` issue is resolved, not sure why it wasn't appearing earlier.

As for the question marks issue, I have some more questions:

1. What happens when you don't configure any icons? Do you see question marks or the defaults (i.e. `d` for directories, `-` for files)?
2. What happens if you change the icons file to use a regular character instead, something like `fi F`, do you start seeing F instead of question marks?
3. I'm assuming your terminal can display the Nerd Fonts icons, but for some reason it doesn't work only when you are using `lf`? One thing I found interesting is that in the fourth screenshot you provided, the preview of the `icons` file says `fi ?`, so it seems like this isn't an issue with icons, but more of the ability of your terminal or `lf` to render this icon. I'm not sure if it will help, but would you be able to show a hexdump your `icons` file? Something like `hexdump -C /path/to/icons` should do. I hope this is not something like a file encoding issue.

**Comment by madrigal1** [comment] 2023-03-17 06:39
Thanks for the response @joelim-work:

* hexdump
![image](https://user-images.githubusercontent.com/30615210/225830245-24699f20-2f91-4768-84b5-076b0dfd9034.png)

* removing icons and using :set icons in lf itself
![image](https://user-images.githubusercontent.com/30615210/225831057-b7586509-7b60-4043-afe4-4060addf20d4.png)

* adding fi F shows F as the icon:
![image](https://user-images.githubusercontent.com/30615210/225831253-2a54981a-35a0-4665-9bca-f08e4155b7b1.png)

**Comment by joelim-work** [comment] 2023-03-17 09:23
Yeah I think your issue has nothing to do with displaying file icons in `lf`, and is more to do with Go handling icon characters. The thing is, icons work perfectly fine for me and most other users too, maybe there's something strange about your system that is causing this? At this point I'm pretty much out of ideas though, apologies for not being more helpful. But we have narrowed down the issue a lot, hopefully @gokcehan or others might have an idea here? 

Otherwise if you do want to go down the rabbit hole and have lots of spare time to play around with Go, there are further things you can try, such as building this project from source and inserting `log.Printf` statements into the code, or creating a [hello world](https://go.dev/tour/welcome/1) project in Go and seeing if you can print out those characters.

**Comment by madrigal1** [comment] 2023-03-17 11:14
Thanks @joelim-work. lf is blazing fast compared to ranger and i will continue to use it. it is a bummer not to have the icons. if you do think of a solution later on do post in the thread as it may help me and future users who may be similar issues. :-)

**Comment by gokcehan** [comment] 2023-03-17 11:53
@madrigal1 @joelim-work Maybe this could be an encoding issue? Can you type `locale` in your terminal and paste the output here? Tcell only supports ascii and utf-8 encodings without registering any other encodings.

**Comment by madrigal1** [comment] 2023-03-17 16:45
Hey @gokcehan thanks for the response:

*locale output
![image](https://user-images.githubusercontent.com/30615210/225967008-3994ffd7-7e5a-4e12-a48d-3e76f3d0e55f.png)

**Comment by gokcehan** [comment] 2023-03-17 18:09
@madrigal1 Maybe you need to run `locale-gen` to update it afterwards though I'm not too familiar with these settings myself and I think it might depend on your system so you should better look it up from somewhere.

**Comment by joelim-work** [comment] 2023-03-18 00:26
If you're using Manjaro, then that is based of Arch Linux and I think you can just follow the [instructions](https://wiki.archlinux.org/title/installation_guide#Localization). The file you define `LANG` in should be `/etc/locale.conf`, not `~/etc/locale.conf`. And you also need to edit `/etc/locale.gen` before running `locale-gen`. I would also suggest to reboot your computer as well after these changes.

I'm not too familiar with locale settings myself, but I'm quite sure the internet has plenty of information for you to look up.

**Comment by joelim-work** [comment] 2023-03-18 06:11
**UPDATE:** I'm pretty sure this is a locale issue, I was able to reproduce all this on my own computer by running `lf` using the default locale:

```shell
LC_ALL=C lf
```

This [StackExchange answer](https://unix.stackexchange.com/a/87763) is a pretty good read, and once you configure your locale settings properly, running `locale` should result in something similar to the given example in there.

**Comment by gokcehan** [comment] 2023-03-20 12:47
@joelim-work Thanks for the help. I have now added some of these instructions as a "troubleshoot" to the new colors and icons wiki page. Feel free to change them accordingly. I don't expect any more replies to this issue so I'm closing it.

**Closed by gokcehan** 2023-03-20 12:47 UTC
