### ISSUE TITLE
Panic with user error on Android

### ISSUE THREAD

**Issue by notevenodd** [gokcehan/lf#108] opened 2018-08-12 19:01 UTC
When I try the pre-built `lf` binary (version r7 of lf-linux-arm.tar.gz) in Android (5.1.1) with [Termux](https://termux.com/), I am getting the following error:

```
2018/08/12 18:45:54 user: user: Current not implemented on linux/arm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x150a88]

goroutine 1 [running]:
main.init.2()
        /home/travis/gopath/src/github.com/gokcehan/lf/os.go:64 +0x544

```

I really would like to be able to run lf from my (non-rooted) Android phone.

**Comment by gokcehan** [comment] 2018-08-12 19:39
@notevenodd We are using `os/user` to get the location of home folder for the user configuration file and it looks like Go does not implement this for android. I can try to disable user configuration on android as a workaround for now. There may probably be other issues afterwards. I have an android phone so I can take a look at it later on.

By the way, I'm curious, is it actually any use to make this work on a mobile phone? It is a keyboard driven applications so I can't imagine how this would be any useful. I remember someone on reddit also asked for android support last time I posted there. Maybe it was you I don't know :)

**Comment by gokcehan** [comment] 2018-08-12 23:34
@notevenodd We are storing the socket file and log files in `/tmp` folder.

`$XDG_RUNTIME_DIR` makes sense, but it should probably default to `/run/user/<uid>` though this is not specified in [xdg spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). There are two more standards for file system hierarchies that I'm aware of, [systemd](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html) and [filesystem hierarchy standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html). Standards are still quite a mess unfortunately so it is probably best to keep runtime files in `os.TempDir` for the while.

I was going to implement `$XDG_RUNTIME_DIR` with a fallback to `os.TempDir` as default, then I realized there is already `$TMPDIR` variable to override `/tmp` on unix systems as described in [os.TempDir](https://golang.org/pkg/os/#TempDir). Can you try to set this variable to see if it works?

**Comment by notevenodd** [comment] 2018-08-13 13:03
> Can you try to set this variable to see if it works?

No, it doesn't work. The program still tries to retrieve the username (which Go stupidly doesn't implement in Android) as you name your socket filename "lf.<username>.sock"

---

I suggest a fix would be to give a static name to the socket: just name it `lf.sock`...
1. in `$XDG_RUNTIME_DIR` (if defined),
1. or alternatively, `$XDG_CACHE_HOME` (if defined),
1. or alternatively in, `~/.cache`

Such change feels reasonable and elegant and:
- it would avoid the socket being **readable by everyone** as is currently the case (stuff in `/tmp` is readable and you're not changing the file permissions)
- by explicitly setting up some `XDG-...` vars when invoking `lf` on Android, one could bypass Go querying user's home and name (in this `init()` function at least, I don't know what it does down the road).

**Comment by gokcehan** [comment] 2018-08-13 21:12
@notevenodd I realized we are using `gUser` variable in many places throughout the code so the program would still fail afterwards even if we change the socket name. Also it turns out `user.Current` call does not actually fail with a runtime panic and the error message on the screen is just part of the log since it can't open a log file either. So instead I thought about filling `gUser` with dummy values when it is empty with something like:

	if gUser == nil {
		gUser = &user.User{HomeDir: ".", Username: "blank"}
	}

This indeed seems to fix the issue and I was able to run a `linux/arm` binary with termux on my android phone. Then I realized go already seems to fill with dummy values on android in [lookup_stubs.go](https://golang.org/src/os/user/lookup_stubs.go). So I think the real issue here is that `linux/arm` is not supposed to run on android. Instead we should use `android/arm` target on android. We don't have it on our cross build script. It was either not available when I prepared the script or it was not building properly. I will check this again with our travis go version. If things go well, we can just add `android/arm` to our cross build script, and it should run on android without a change.

Also maybe we should change permissions of socket and log files so they won't be readable by others.

**Comment by gokcehan** [comment] 2018-08-14 20:14
@notevenodd I tried to build `android/arm` on my linux but it fails with a missing `gcc -marm` flag error. It seems that `android` target is meant to be used with android ndk. So I think I was wrong about `android/arm` being a better fit than `linux/arm` for termux.

Looking at [lookup_stubs.go](https://golang.org/src/os/user/lookup_stubs.go), I realized there is another fallback mechanism to read `$USER` and `$HOME` variables. On my phone, termux sets the `$HOME` variable properly but not the `$USER` variable. By setting `$USER` variable to a dummy value, the fallback mechanism starts to work as intended. So in the end, all we need is to run the program as such:

    USER=android lf

I think it makes sense to set a `$USER` variable in one of shell init files so other go programs that use `os/user` also works properly. Maybe termux developers would consider doing this by default out-of-the-box.

**Comment by notevenodd** [comment] 2018-08-15 19:48
Great! Setting up the USER variable makes it work for me. I can have this now on android: ˋalias lf='USER=$(whoami) lf'ˋ

Awesome. Issue can be closed and probably this workaround should be mentionned on the project page.

I guess it's login(1) who sets the $USER variable in regular Linux, and of course it's different in Adnroid and Termux. Yes, perhaps we should propose that Termux could add the USER variable as an enhancement (although of course, it's a little odd that Go requires this)

**Comment by gokcehan** [comment] 2018-08-15 20:14
@notevenodd I'm thinking of adding a troubleshoot wiki page. This can go in there.

By the way, if I set USER to empty on my linux machine, I get the same error:

    USER= lf

So this does not seem to be a fallback mechanism as I called it, but the regular mechanism instead. I wonder if there are other unix machines out there not setting either `$HOME` or `$USER` variables. Maybe we should consider failing with a more informative error message. Error message in Go does not seem to be of much help without reading the source. Or maybe it would be easier just to use dummy values when these variables are empty. Let's keep this issue open for a while.

**Comment by gokcehan** [comment] 2018-08-29 15:23
I have added some extra error messages when either of these variables are empty. I thought about using dummy values but there doesn't seem to be a good dummy value for `$HOME` variable. We would not want to end up creating history and mark files in random directories. So maybe it is best to fail at startup when these variables are empty. Closing this issue now.

**Closed by gokcehan** 2018-08-29 15:23 UTC
Labels: bug
