### ISSUE TITLE
Umount: target busy after using lf

### ISSUE THREAD

**Issue by rpolve** [gokcehan/lf#287] opened 2020-01-15 10:16 UTC
version r13

Hi,

I opened _lf_ in an external drive with _-last-dir-path_ option, copied and deleted some files for a couple of G total, then exited

Several minutes later, I was unable to unmount the device because of some lf process taking hold of it.

```
$ sudo umount /mnt
umount: /mnt: target is busy.
$ fuser -vm /mnt
                     USER        PID ACCESS COMMAND
/mnt:                root     kernel mount /mnt
                     polve     54766 ..c.. lf
```

**Comment by bcaccia** [comment] 2020-01-17 14:59
Unable to reproduce this issue using the following setup:

* lf r13
* [Luke Smith ST fork(st 0.8.2)](https://github.com/lukesmithxyz/st) 
* i3 version 4.14.1
* Kubuntu 18.04

The steps taken to try to reproduce were:

1. Start with `./lf --last-dir-path test.txt /media/PATHTOTHUMBDRIVE`
2. Copy 305mb video file to external thumb drive 5 times by:
  a. Press `y` to copy file
  b. Navigate to thumb drive and press `p` to paste
3. Delete all 5 copies of video file from thumb drive by:
  a. Place highlight cursor over target file
  b. Type in `:delete` to delete
4. Quit lf
5. Unmount thumb drive using `umount NAMEOFTHUMBDRIVE`

I confirmed that the `--last-dir-path` file was correctly written to the thumb drive after performing the reproduction.

**Comment by machinedgod** [comment] 2020-01-17 16:14
This happened to me yesterday - but I'm not sure why exactly.
I used `lsof` to find 4 `lf` instances holding the lock, and `killall` worked fine.

I'm launching `lf` without the shell (`urxvtc -e lf`), and I am mounting/unmounting the volumes with custom commands, if that helps:
```
map Mm :{{
    $mount $f
    reload
}}

map Mu :{{
    $umount $f
    reload
}}
```

**Comment by Monirzadeh** [comment] 2020-01-21 21:36
test that command and again try to umount
```
pkill lf; rm /tmp/lf.${USER}*
```

**Comment by shabahengam** [comment] 2020-01-22 19:01
let me explain why this happens:
lf uses a client/server architecture so when you run lf **for the first time**,lf run the client/server together.when you press `q` and close lf you actually just close the client but server still running and keep busy the path(e.g. your partition). run `ps aux | grep lf` and check the server PID.then check the `cwd` of that PID(`ls /proc/PID/cwd`)you will see that it is the path that you did run lf for the first time.
now you have two options:
1.don't run lf for the first time on the partition that you want to unmount cause server will keep it busy.
2.kill all the lf process (like @Monirzadeh said) and unmount your partition.
**P.S.** my english is not very good so i hope you understand my explanation.

**Comment by machinedgod** [comment] 2020-01-23 11:53
Would it be an acceptable change to make it close the server as well, when the last instance of client is closed - unless server is -somehow- ran manually as a daemon?

**Comment by gokcehan** [comment] 2020-03-18 20:21
@shabahengam Thanks for identifying the issue. If this is the case, can we not just change the current directory to the home directory before running the server process to fix the issue?

**Comment by shabahengam** [comment] 2020-03-19 15:52
@gokcehan  Yes,it will be good if the first instance of lf starts in Home directory but I have little experience with Go and I don't know how this should be done.Sorry

**Comment by gokcehan** [comment] 2020-07-04 00:44
I have now changed the directory of server process to the home directory. This issue should be resolved with the new behavior. Closing the issue. Feel free to leave further comments if the issue persists.

**Closed by gokcehan** 2020-07-04 00:44 UTC
Labels: bug
