### ISSUE TITLE
Wierd interaction when using % Shell-Command and Input

### ISSUE THREAD

**Issue by SPFabGerman** [gokcehan/lf#275] opened 2019-12-21 11:27 UTC
When using `%` to start an command in lf that expects input from the user, lf automatically places the file information after the cursor when you start typing something.

As an Example: I type `%read temp` and hit enter. Now lf shows me the `>` prompt as expected and I can type something. But as soon as I hit the first character, lf inputs the file information before my character. E.g. if I type `a` it shows: `>-rw-rw-rw- 4.7K 17 Dec 2019 14:01:49a`.
The file Information isn't recognized by the command and therefor only visible to the user.

An additional error with the `%` Command is also, that lf doesn't seem to send Enter key presses to the command, if there is no other input.

Using again the above example: when lf shows me the `>` prompt and I type Enter, nothing happens. Only if I first type another character lf seems to send further Enter presses to the command. When I type and then delete a character and then press Enter again, nothing happens.

This is really annoying, if I want to confirm something with just an normal Enter press.

When using `$` Command everything works fine, but I don't see lf anymore for the duration of the command. (As expected.)

I am using the r13 Release.

**Comment by gokcehan** [comment] 2019-12-22 21:02
@SPFabGerman Looks like I have somehow broken how `%` commands take input at some point. We used to be able to run commands like `%mv -i src dst` and we were able answer simple prompts ilke `y` and `n` but it's currently not working. I will try to fix this again.

Beside this however, `%` commands and `read` shell builtin do not work well together as they both try to take control of the terminal input. `%` command is already quite fragile and it is intended for simple commands with optionally simple prompts like `y` and `n`. What kind of custom command you're currently trying to come up with?

**Comment by gokcehan** [comment] 2019-12-23 13:39
@SPFabGerman I have reverted the patch which broke `%` commands. Things like `mv -i foo bar` should be working as intended now. I'm not sure about `read` builtin though.

I will keep this issue open for a while until we can fix error cleaning issue of the reverted commit.

**Comment by SPFabGerman** [comment] 2019-12-23 15:11
> What kind of custom command you're currently trying to come up with?

I just tried modifing the `delete` example from the given lfrc file to work inline. For that I just changed the `$` to an `%` and then I encountered these bugs.
That's also where I took the `read` example from.

For reference, this is what I tried:
(It is basically identical to the example file, but it has an `%`)

```
cmd delete %{{
    set -f
    printf "$fx\n"
    printf "delete? [y/N]"
    read ans
    [ "$ans" = "y" ] && rm -rf $fx
}}
```

**Comment by 0x4c47** [comment] 2020-04-07 21:02
Does anyone know of a way to shell (or otherwise) script/code this in a way where "read" or an alternative doesn't behave that weird and can be used consistently with %? Any alternative to read that is more compatible?
Because that would greatly improve the usefulness of %. Anything with basic one line input could then be implemented in a really nice way just like built-in commands like :rename.

**Comment by gokcehan** [comment] 2020-04-13 16:06
I have now pushed a new release that contains the reverted patch mentioned here. Closing this issue now.

**Closed by gokcehan** 2020-04-13 16:06 UTC
Labels: bug
