### ISSUE TITLE
Seg fault on OpenBSD 6.4

### ISSUE THREAD

**Issue by greenfork** [gokcehan/lf#110] opened 2018-10-27 19:24 UTC
I have downloaded a release file for amd64 and run it on OpenBSD 6.4. It crashed with the `lf.core` file attached to this post.

OpenBSD updated from 6.3 to 6.4 on the 18th of October, this may be related.

[lf.core.zip](https://github.com/gokcehan/lf/files/2522138/lf.core.zip)

**Comment by gokcehan** [comment] 2018-10-29 16:00
@greenfork Thanks for reporting.

I found the following in [Go1.11 release notes](https://golang.org/doc/go1.11):

> Go 1.11 supports the upcoming OpenBSD 6.4 release. Due to changes in the OpenBSD kernel, older versions of Go will not work on OpenBSD 6.4.

So it is likely to be related to OpenBSD version upgrade as you suggested. It looks like travis used 1.10.4 in the last build. They may have already upgraded to Go1.11 by default which should fix this issue. I will take a look at this in the next release. In the meantime, feel free to try building from source yourself if you have go installed.

**Comment by gokcehan** [comment] 2019-02-21 21:14
@greenfork I have set up an OpenBSD virtual machine and tried prebuilt binaries. I can reproduce the segfault in r8 and r9 but r10 seems to run without a problem. There is still the issue of requiring multiple keystrokes which is tracked in #139. Closing this issue now. Freel free to report here if the problems occurs again.

**Closed by gokcehan** 2019-02-21 21:14 UTC
Labels: bug
