### ISSUE TITLE
Pass width of preview panel as argument to preview script.

### ISSUE THREAD

**Issue by zeda-para-iba** [gokcehan/lf#319] opened 2020-04-07 11:49 UTC
I like to preview my manpages in lf, but man needs the width of the text to be output, and lf do not pass the width of the pane to the preview script.

It would be handy if lf passed the width of the preview pane as an argument to the preview script.

In the image below, you can see how lf renders the output of `man(1)`, cutting the end of each line that is longer than the preview pane.

![lf](https://user-images.githubusercontent.com/63294608/78665446-352bea80-78ac-11ea-90ca-1a37bdb3a5cf.png)

**Comment by Provessor** [comment] 2020-04-22 14:28
@zeda-para-iba This is currently part of my preview script enhancement PR #304 if you would like it now. With the current internal data structures this enhancement isn't trivial, however if somebody's interested, feel free to steal the relevant pieces from my PR to try and get this merged sooner.

**Comment by wincent** [comment] 2020-05-27 00:27
I'd find the width handy for other uses too in the preview script.

**Comment by MahouShoujoMivutilde** [comment] 2020-07-02 20:15
As a workaround, if you know your `ratios` - you can calculate width right in `scope`.

Assuming `set ratios 1:2:3` (default):

```sh
# inside your scope
WIDTH="$(( $(tput cols) / 2))"
```

(warning: bashism).

Obviously, it wont work if you change `ratios` on the fly.

**Comment by rafi** [comment] 2020-10-12 17:36
@Provessor looks like #304 is closed. Are there any other efforts on providing width to previewer?

**Comment by gokcehan** [comment] 2020-10-13 01:32
@rafi @Provessor At some point, I intended to go over that PR and import some of the useful bits to the base like the `cleaner` option or this previewer width thing, but then I got distracted to other things. I'm struggling with time management so I try to avoid working on new additions. If anyone bothers to separate the relevant logic and make a pull request, I would be happy to accept the patch.

**Comment by Provessor** [comment] 2020-10-13 03:37
@rafi I'm still working on it over at https://gitlab.com/Provessor/lfp.

@gokcehan I could submit a patch for that quite easily, the problem is with async preview generation it has to finish in the correct order to ensure the correct preview is shown outside of lf. Also it may crash lf under certain circumstances with the current async method.

I have yet to find a good way to implement async with long running previewers without changing the rest of the codebase too much.

**Comment by gokcehan** [comment] 2021-01-24 15:08
This is now available in r19 release.

**Closed by gokcehan** 2021-01-24 15:08 UTC
Labels: enhancement
