### ISSUE TITLE
panic when pressing 'space' in empty direcotry

### ISSUE THREAD

**Issue by adamjedlicka** [gokcehan/lf#23] opened 2016-10-04 14:46 UTC
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x182290, 0x1050c030)
        /usr/lib/go/src/runtime/panic.go:500 +0x33c
main.(*Nav).currPath(0x105697a0, 0x0, 0x0)
        /home/alarm/dev/go/src/github.com/gokcehan/lf/nav.go:427 +0x70
main.(*Nav).toggle(0x105697a0)
        /home/alarm/dev/go/src/github.com/gokcehan/lf/nav.go:347 +0x1c
main.(*CallExpr).eval(0x10568fc0, 0x1056e3b8, 0x0, 0x0, 0x0)
        /home/alarm/dev/go/src/github.com/gokcehan/lf/eval.go:282 +0x21d4
main.(*App).handleInp(0x1056e3b8)
        /home/alarm/dev/go/src/github.com/gokcehan/lf/app.go:69 +0x310
main.client()
        /home/alarm/dev/go/src/github.com/gokcehan/lf/client.go:57 +0x54c
main.main()
        /home/alarm/dev/go/src/github.com/gokcehan/lf/main.go:101 +0x440

**Comment by KenjiTakahashi** [comment] 2016-10-04 20:06
Well, obviously we're not handling the case of selecting a file if there isn't any. I wonder where this should be handled. Probably the cleanest (conceptually) solution would be for `currPath` (and `currFile`?) to return error in such case. But I'm afraid this will quickly turn annoying in practice.

**Comment by adamjedlicka** [comment] 2016-10-05 05:54
I haven't read the codebase so I can't help you much with this. I just created this issue because I don't think its good to panic and kill the program in any circumstances. And this happens on simple key press.

**Comment by gokcehan** [comment] 2016-10-05 08:22
You're absolutely right @adamjedlicka . Panic is definitely not acceptable for these things. We only panic for major exceptions in a few places in `lf` (e.g. initialize termbox). In this case it's an array out of bounds exception by the runtime. So we can't avoid it but only fix it. There were a few such errors previously for empty directories so I spent some time thinking about how to refactor the code to avoid these errors but I couldn't find an easy way. These should be rare though and we should get stable in time. I will try to take care of this as soon as possible. Thanks for the report.

**Comment by KenjiTakahashi** [comment] 2016-10-05 12:08
Sure, @adamjedlicka, thanks for taking your time to report. My comment was intended to whoever is willing to work on it, to know better what's going on in code.
I will try to get back to #20 in the coming days, hopefully I'll scratch this one on the way as well.

**Comment by gokcehan** [comment] 2016-10-07 09:00
@adamjedlicka With the latest commit toggling and yanking in an empty directory doesn't seem to cause any trouble. Closing this issue now. Feel free to open again if you continue to have problems after you update to the latest version.

**Closed by gokcehan** 2016-10-07 09:00 UTC
