### ISSUE TITLE
lf doesn’t select

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#370] opened 2020-06-03 14:54 UTC
[`~/.config/lf/lfrc`][`lfrc`]

``` lf
# Commands ─────────────────────────────────────────────────────────────────────

cmd create-new-file ${{
  printf 'new-file:'
  read file
  if test -z "$file"; then
    exit 1
  fi
  directory=$(dirname "$file")
  mkdir -p "$directory"
  touch "$file"
  lf -remote "send $id select $file"
}}

cmd create-new-directory ${{
  printf 'new-directory:'
  read directory
  if test -z "$directory"; then
    exit 1
  fi
  mkdir -p "$directory"
  lf -remote "send $id select $directory"
}}

# Mappings ─────────────────────────────────────────────────────────────────────

map <f-2> create-new-file
map <f-3> create-new-directory
```

[`lfrc`]: https://github.com/alexherbo2/configuration/blob/master/config/lf/lfrc

**Comment by gokcehan** [comment] 2020-06-06 20:48
This is a duplicate of #165. Try to add `lf -remote "send $id load"` as mentioned in the other issue to see if it works. Closing this issue.

**Comment by gokcehan** [comment] 2020-07-03 16:42
Reopening to investigate why `load` does not work with `$` commands.

**Comment by gokcehan** [comment] 2020-07-16 23:29
With the latest update, this should now work without an issue with any type of command, and `load` is redundant since it is already automatically called after shell commands. Closing this issue.

**Closed by gokcehan** 2020-07-16 23:29 UTC
Labels: bug
