### ISSUE TITLE
Build on OpenBSD 6.4 freezes after start

### ISSUE THREAD

**Issue by greenfork** [gokcehan/lf#115] opened 2018-11-11 10:54 UTC
I have built an `lf` binary and run it. But it fails to respond to any of the keypresses at all. Loads the initial screen with directories and stops from there.

```
$ cd
$ go get -u github.com/gokcehan/lf
## same with env CGO_ENABLED=0 go get -u -ldflags="-s -w" github.com/gokcehan/lf
$ ./go/bin/lf
```

Versions:
```
OpenBSD 6.4
go version go1.11 openbsd/amd64
st 0.8.1 (terminal emulator)
tmux built in OpenBSD
```

**Comment by gokcehan** [comment] 2018-11-11 16:02
@greenfork It sounds strange. Is there anything relevant to this in the log file? Can you maybe try to run one of the example programs that comes with termbox like `keyboard.go`:

    go run ~/go/src/github.com/nsf/termbox-go/_demos/keyboard.go

This might help to see if this is a termbox related issue or not.

Also, you mention `st` and `tmux`. Have you tried it on a different terminal emulator and/or without `tmux`?

Do you think this may be related to OpenBSD 6.4 update you mention in #110 ?

**Comment by gokcehan** [comment] 2019-02-17 17:15
@greenfork It seems that someone pushed a [commit](https://github.com/nsf/termbox-go/commit/0938b5187e61bb8c4dcac2b0a9cf4047d83784fc) to termbox-go to fix a problem with OpenBSD which may be related to this. If you still haven't give up on this, can you maybe give this a try again with the latest termbox-go version?

Also I think if this works and [r10](https://github.com/gokcehan/lf/releases/tag/r10) prebuilt binary still has a segfault, then we can be sure that #110 is a different issue which is likely about the go version as travis still uses Go1.10 by default.

**Comment by gokcehan** [comment] 2019-02-21 21:18
@greenfork I have now tried termbox-go with and without the commit I mentioned on an OpenBSD virtual machine. Before the commit, termbox applications fail to respond all keystrokes. After the commit, keys are working but quitting applications require a few extra keystrokes to work as reported in #139. So the problem is still somehow there, but it is less severe. Closing this issue in favor of #139.

**Closed by gokcehan** 2019-02-21 21:18 UTC
Labels: bug
