### ISSUE TITLE
Watch the current directory for newly created files

### ISSUE THREAD

**Issue by lenormf** [gokcehan/lf#73] opened 2017-04-06 11:48 UTC
Hi,

How easy would it be to watch the current working directory for new files, and subsequently automatically refresh the view?

Thanks.

**Comment by gokcehan** [comment] 2017-04-06 12:11
This was also proposed by @KenjiTakahashi 

The problem is that Go standard library does not have a filesystem API. Without such an API we need to work on each platform differently since they have different notification systems. This is not an easy task and I don't think we have the man power for this in our project.

So our only option is to use a third party library. There is [fsnotify](https://github.com/fsnotify/fsnotify) that I'm aware of. At some point, [it was considered to be added to the standard library](https://fsnotify.org/) but I think they gave up on that. Last time I checked their issues, maintainer was looking for others to distribute the maintenance effort. So I have my doubts about the stability of this project. This is pure speculation though and I never tried to use this library myself yet.

So I like the idea of using filesystem notifications for a file manager but I'm hesitant to add a third party library dependency for it which may give us headaches later on since it will most likely spread all over our codebase.

**Comment by KenjiTakahashi** [comment] 2017-04-08 17:39
I actually planned to use [rjeczalik/notify](https://github.com/rjeczalik/notify) instead. It may seem less popular, but it provides a better abstraction and is maintained. It is also used by cortesi tools (among others), which are in turn used by many people, so it should provide a good measure.

Either way, there are multiple problems here:
1. macOS is not doable without CGo and IOKit. This makes cross compilation for Darwin practically impossible.
2. Both BSD kqueue and macOS FSEvents are not very performant, it sometimes takes 20-30 seconds to deliver the event. I've also found that under heavy load (in the system, not necessarily your app), they might even drop the event completely, without delivering it.
3. None of them (AFAIK) work for user space FSes, such as SSHFS and NFS (with the exception of the FSEvents and NFS combo, because it's both Apple ;-]).

So, in my experience, the only reliable systems here are inotify (Linux only) and the Windows one (with long name that I don't remember :-)).

In the end, I think I'd rather resolve to just use a polling goroutine. If done right, it shouldn't take that much resources and will work everywhere with much less effort.

**Comment by dumblob** [comment] 2017-04-18 18:44
>In the end, I think I'd rather resolve to just use a polling goroutine. If done right, it shouldn't take that much resources and will work everywhere with much less effort.

My words.

**Comment by cstrahan** [comment] 2017-10-31 17:47
FWIW, I'd like to point out Facebook's watchman, which is a cross platform (at least Windows, Mac & Linux) file system watching daemon. I've used it for a number of years now (I'm also maintain the package in NixOS), and it works great.

* https://github.com/facebook/watchman
* https://facebook.github.io/watchman/

**Comment by gokcehan** [comment] 2017-10-31 19:42
@cstrahan It looks nice but it seems to be written in C++ which would break our static linking. Also it seems like a standalone tool and I couldn't find whether or not it is possible to use it as a library as well.

**Comment by cstrahan** [comment] 2017-10-31 20:29
> @cstrahan It looks nice but it seems to be written in C++ which would break our static linking. Also it seems like a standalone tool and I couldn't find whether or not it is possible to use it as a library as well.

Correct. If you were to go with `watchman`, it's use would require that the user have `watchman` already installed. It's totally understandable if you want to keep everything self-contained as one binary; I just figured I'd point out the option, in case it hadn't been considered.

**Comment by gokcehan** [comment] 2018-06-09 19:11
I have now added `period` option to control periodic refreshes. This is in terms of seconds to prevent people from setting this value too low. Even though refresh is quite efficient, setting this to a value like 10 milliseconds or less can do a lot of stat calls and be a performance bottleneck. Setting it to 0 disables periodic refreshes which is also the default behavior. I am closing this issue. Feel free to test this and report problems here.

**Closed by gokcehan** 2018-06-09 19:11 UTC
Labels: enhancement
