### ISSUE TITLE
Remove invert for select all / clear all selections

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#180] opened 2019-06-16 20:23 UTC

**Comment by gokcehan** [comment] 2019-06-16 21:17
@alexherbo2 Sorry, I can't make anything out of your title. Can you describe what you want using more words pls?

**Comment by gokcehan** [comment] 2020-07-08 01:42
I think this is a duplicate of #178. Closing for the lack of further discussion feedback.

**Closed by gokcehan** 2020-07-08 01:42 UTC
Labels: duplicate
