### ISSUE TITLE
icons: file type vs. file extension

### ISSUE THREAD

**Issue by j-xella** [gokcehan/lf#1322] opened 2023-06-28 11:10 UTC
It seems that when determining file icon (same with colours?), file type takes priority over extension.  For example, when I use nerd fonts, executable file always has the rocket icon, even if a better icon can be found by extension.

I understand that some people may like this, but if I don't, there is no way to change it. Commenting out "ex" entry in `colors` file will result in lf using the default `x` for the file icon.

Ideally, I would like the ability to specify not just which icon (color?) to use for particular file type/extension, but also which method should take priority. Also, for each file type/extension, it would be great to be able to disable the icon at all. Maybe by having an optional 3rd column with "importance/weight" number?

**Comment by joelim-work** [comment] 2023-09-29 04:30
Duplicate of #992

**Closed by joelim-work** 2023-09-29 04:30 UTC
Labels: duplicate
