### ISSUE TITLE
'quit' command doesn't immediately quit

### ISSUE THREAD

**Issue by jocap** [gokcehan/lf#139] opened 2019-02-18 22:21 UTC
OS: OpenBSD 6.4
Release: r10

When I type 'q', I expect lf to quit immediately. What happens instead is nothing. I have to press another key to get lf to quit -- sometimes even two or three.

That is, 'q' alone doesn't quit. 'qq' sometimes quits. 'qqw' sometimes quits.

Any ideas?

**Comment by gokcehan** [comment] 2019-02-19 12:09
@jocap There are currently two more bugs reported in OpenBSD, #110 and #115, which may be related to this. It seems that OpenBSD has been making breaking changes lately. It would be nice if we have someone to asses the current situation in OpenBSD, by manually compiling from the source with Go1.11+ and the latest termbox-go version. If not, I will try to set up an OpenBSD virtual machine at some point though it can take some time and I'm not familiar with BSDs.

**Comment by jocap** [comment] 2019-02-19 22:10
gokcehan wrote:
> It would be nice if we have someone to asses the current situation in
> OpenBSD, by manually compiling from the source with Go1.11+ and the
> latest termbox-go version.

I tried this:

    go get -u github.com/nsf/termbox-go
    go get -u github.com/gokcehan/lf

`~/go/bin/lf` has the problem I described earlier.

**Comment by gokcehan** [comment] 2019-02-20 12:34
@jocap Thanks for helping out for this. Can you confirm you have Go1.11 installed? Also can you try one of the demo programs that comes with termbox-go to see if the problem is termbox related or not?

    go run ~/go/src/github.com/nsf/termbox-go/_demos/keyboard.go
    # or other demos in this directory

**Comment by jocap** [comment] 2019-02-20 15:25
gokcehan wrote:
> Can you confirm you have Go1.11 installed?

Indeed: go-1.11 (installed)

> Also can you try one of the demo programs that comes with termbox-go
> to see if the problem is termbox related or not?
> 
>     go run ~/go/src/github.com/nsf/termbox-go/_demos/keyboard.go
>     # or other demos in this directory

Indeed, the problem seems to be with termbox.  I have the same issue
with keyboard.go.

**Comment by gokcehan** [comment] 2019-02-21 21:26
@jocap So I have set up an OpenBSD virtual machine to see it for myself. As I mentioned in the other issue, it seems that [OpenBSD workaround commit](https://github.com/nsf/termbox-go/commit/0938b5187e61bb8c4dcac2b0a9cf4047d83784fc) pushed on Jan 4 made this problem much less severe than before. I guess there are some people that are aware of this and they are working on to fix it though I have not found a related issue in termbox-go to track this.

**Comment by jocap** [comment] 2019-02-21 22:16
gokcehan wrote:
> As I mentioned in the other issue, it seems that OpenBSD workaround
> commit pushed on Jan 4 made this problem much less severe than before.

Thanks for pointing me to this.

> I guess there are some people that are aware of this and they are
> working on to fix it though I have not found a related issue in
> termbox-go to track this.

Hopefully :-)

**Comment by gokcehan** [comment] 2020-10-20 21:40
We have already changed from termbox to tcell which is available in r17 and this issue is likely fixed. Closing this issue now. Feel free to leave further comments here if the issue persists.

**Closed by gokcehan** 2020-10-20 21:40 UTC
Labels: bug

**Comment by Limero** [comment] 2023-02-08 17:56
I installed OpenBSD 7.2 and lf from the official repos (`pkg_add lf`) and had this issue. They still seem to ship r22.

After manually building latest master from git (r28), I can confirm that this is no longer an issue and lf seems to work the same as on Linux :tada:
