### ISSUE TITLE
Reload previews on window size change

### ISSUE THREAD

**Issue by UtkarshVerma** [gokcehan/lf#1095] opened 2023-01-29 09:40 UTC
Would it be possible to have previews reloaded when the terminal size changes, that is `WINCH` is passed to the process?

For example, the image should be positioned inside the preview pane, rather than overflowing:

https://user-images.githubusercontent.com/31820255/215317973-a7c9bca2-0701-4631-8964-fa93c771d7f2.mp4

**Comment by DusanLesan** [comment] 2023-01-29 14:28
Hi Utkarsh. I think this is a duplicate of https://github.com/gokcehan/lf/issues/1055. It luckily has a PR open

**Comment by joelim-work** [comment] 2023-02-12 01:31
Hi @UtkarshVerma, the pull request #1074 has now been merged. Please close this issue as it has now been fixed.

**Closed** 2023-02-12 07:27 UTC
