### ISSUE TITLE
set shell nu

### ISSUE THREAD

**Issue by yashamon** [gokcehan/lf#1015] opened 2022-11-17 17:25 UTC
Is this supported on windows? Setting shell to nu, precludes running any shell commands. The error is something like: invalid current directory

Also how do I see shell errors within lf? They are not in the log. 
Actually setting shell to pwsh also throws some kind of error when running shell commands (I can't see what it is) but it is ignored and commands go through.

**Comment by joelim-work** [comment] 2024-06-24 14:30
Closing this as a duplicate of #1303

**Closed by joelim-work** 2024-06-24 14:30 UTC
Labels: duplicate
