### ISSUE TITLE
panic with a shell command on startup

### ISSUE THREAD

**Issue by Naheel-Azawy** [gokcehan/lf#459] opened 2020-09-01 20:05 UTC
Hi, I just tried `lf` on a raspberry pi zero w. Here's what I got:

```
panic: send on closed channel

                             goroutine 11 [running]:
                                                    main.startEventListening.func2(0x101ad40, 0x101ad80)
                        /home/pi/go/src/github.com/gokcehan/lf/ui.go:487 +0x90
                                                                              created by main.startEventListening
                                /home/pi/go/src/github.com/gokcehan/lf/ui.go:461 +0x90
```

Any idea?

**Comment by gokcehan** [comment] 2020-09-01 21:14
@Naheel-Azawy I think this is one of the functions introduced in the latest tcell port patch, though we had a similar structure before so I doubt it's related. Just to be sure, is this the first time you tried this on pi? Does older versions or prebuilt binaries work?

**Comment by Naheel-Azawy** [comment] 2020-09-01 21:32
@gokcehan Yes it is the first time I tried this on a pi. I have just updated `lf` on my main machine and it output the same error..
I tried again on the pi, it works well outside tmux. Dies under tmux. The same case on my main machine. So it appears to be a problem with tmux and has nothing to do with the pi. Still not sure why though.

**Comment by gokcehan** [comment] 2020-09-01 22:07
@Naheel-Azawy This sounds strange. Can you confirm it was working inside and outside of tmux in r16, and now it only works outside of tmux and crashes with the above error inside tmux in master?

**Comment by Naheel-Azawy** [comment] 2020-09-02 18:31
I hope this video explains what's happening

https://youtu.be/UI4ezwL1bj0

**Comment by haomingw** [comment] 2020-09-04 01:27
I have the same issue, under terminal I've tried go 1.15.1 and 1.14.8, both don't work.

**Comment by gokcehan** [comment] 2020-09-04 09:15
I'm marking this as a bug, though I still can't reproduce it on my machine.

@Naheel-Azawy @haomingw Can you provide more information that could help me identify the issue? Did you try this without `tmux.conf` and/or `lfrc`? What terminal are you using?

cc @Provessor

**Comment by gokcehan** [comment] 2020-09-04 09:21
@Naheel-Azawy @haomingw Also do you have anything relevant in your log files after the crash?

**Comment by haomingw** [comment] 2020-09-04 09:21
Thanks for your advice @gokcehan. Without lfrc all works fine, I will check my configuration file

**Comment by haomingw** [comment] 2020-09-04 09:27
lf crashes because of this line in my lfrc which works fine before:
`$[ -d ~/.trash ] || mkdir -p ~/.trash`

**Comment by Provessor** [comment] 2020-09-04 10:13
@gokcehan @haomingw that panic seems to be because it is trying to send an event to `ui.evChan` while the UI is paused during startup. I haven't narrowed down the other one yet but that should be fixable by properly quitting from both those `startEventListening` goroutines when it pauses instead of waiting for the dead screen event from tcell.

**Comment by gokcehan** [comment] 2020-09-04 10:17
@haomingw I'm not able to reproduce the error on my machine. As a workaround for now, you can change the command type from  `$` to `%`, which doesn't pause the ui.

@Naheel-Azawy It happens on all terminals I have installed, regardless of whether it's inside tmux or not. Maybe you have a custom command that only runs in tmux?

**Comment by gokcehan** [comment] 2020-09-04 10:30
@Provessor Deleting the line `close(ui.evChan)` in `ui.resume` seems to fix the problem. Do you think it's wise to do that? Doesn't garbage collection handle closing the channel?

**Comment by gokcehan** [comment] 2020-09-04 10:40
@Provessor Nope sorry spoke too early. Without that line, we don't seem resume operation after a shell command.

**Comment by Provessor** [comment] 2020-09-04 10:48
@Naheel-Azawy I had a look at your [dotfiles on GitHub](https://github.com/Naheel-Azawy/naheel-dotfiles) and copied the lfrc.sh and tmux.conf onto my system and don't get any issues inside or outside tmux with xterm or st, are these up-to-date?

@gokcehan it seems a channel that is no longer used will get cleaned up so it could be forgotten provided the goroutines always exit when necessary.

**Comment by gokcehan** [comment] 2020-09-04 11:09
@Provessor Without the line `close(ui.evChan)` crash is fixed, though when you run a shell command after the startup, you don't receive events anymore after it returns.

As a side note, I'm able to reproduce the error on my machine with nothing but a simple shell command in `lfrc` (e.g. `$ls`), with or without tmux on many different terminals I have installed. It's kind of strange @Naheel-Azawy only experiences this with tmux.

**Comment by Provessor** [comment] 2020-09-04 11:24
@gokcehan 
> Without the line close(ui.evChan) crash is fixed, though when you run a shell command after the startup, you don't receive events anymore after it returns.

I've been slowly tracking the event through to try and work out why it gets caught, the events aren't making it back down to `ui.readEvent` but do get past both the `startEventListening` goroutines.

**Comment by gokcehan** [comment] 2020-09-04 15:11
@Provessor Creating a new goroutine for each resume does not seem to be a good approach for this. I have pushed a fix to use the same goroutine for input reading and only update `ui.screen` when resuming which seems to work well for this issue. Let me know if this approach is not appropriate.

**Comment by gokcehan** [comment] 2020-09-04 15:27
@Provessor I have also went ahead and removed our old escape delaying mechanism for alt keys as tcell seems to implement it by itself somehow. One less goroutine now to worry about.

**Comment by Naheel-Azawy** [comment] 2020-09-04 16:22
Oh wow.. The discussion here went way faster that I expected. Sorry for my slow response I've been too busy...

> @haomingw I'm now able to reproduce the error on my machine. As a workaround for now, you can change the command type from `$` to `%`, which doesn't pause the ui.
> 
> EDIT: not -> now
> 
> @Naheel-Azawy It happens on all terminals I have installed, regardless of whether it's inside tmux or not. Maybe you have a custom command that only runs in tmux?

Yep, looks like this was the thing. I tried digging more on my configs and I found what was the reason. I use `fish` inside of `tmux` and `bash` outside of it. In `fish`, I do have a custom command for `lf` right [here](https://github.com/Naheel-Azawy/naheel-dotfiles/blob/master/configs/fish-config.fish#L109). So it looks like the `$printf` was the one stopping it. using `%` did help as a workaround. But then after pulling the latest updates it works anyway. Thanks!

> @Naheel-Azawy I had a look at your [dotfiles on GitHub](https://github.com/Naheel-Azawy/naheel-dotfiles) and copied the lfrc.sh and tmux.conf onto my system and don't get any issues inside or outside tmux with xterm or st, are these up-to-date?

@Provessor I'm sorry you had to look that far in my messy dots.. Yeah they are up to date. I use `st` but anyway, that has nothing to do with the problem. I guess it's now clear to us.

It's funny that I thought it was a problem only with the pi then I put the blame on tmux and now it looks like they're both innocent of that. Anyone suggest a better title for this issue?

**Comment by gokcehan** [comment] 2020-09-04 17:52
@Naheel-Azawy You can rename it anything you like without tmux, maybe "panic with a shell command on startup". I feel like we are ready to close the issue anyways. It's best to wait for @Provessor confirmation, as he might be more familiar to tcell than me. In the meantime, @Naheel-Azawy and @haomingw you can check the master to confirm that the issue is indeed resolved if you haven't already.

**Comment by Naheel-Azawy** [comment] 2020-09-04 18:04
@gokcehan I just double checked, master is working pretty well apparently for now.

**Comment by Provessor** [comment] 2020-09-05 03:22
@gokcehan apart from #461 this looks good to me, I wasn't aware tcell could handle when to turn those escape commands into modifiers.

**Closed** 2020-09-05 09:42 UTC
Labels: bug
