### ISSUE TITLE
Tagging an entry doesn't update the rightmost panel

### ISSUE THREAD

**Issue by lenormf** [gokcehan/lf#64] opened 2017-03-07 10:59 UTC
Hi,

Upon marking an entry, the cursor jumps to the next entry in the main column, and the panel on the right isn't updated when the entry is a directory (it's supposed to list the files in the directory, which right after the one that was marked).

Thanks.

**Comment by KenjiTakahashi** [comment] 2017-03-07 12:27
True, same thing happens for file previews.

**Comment by KenjiTakahashi** [comment] 2017-03-07 13:16
Why close ;-)?

**Comment by lenormf** [comment] 2017-03-07 13:18
Hit the wrong button in a hurry!

**Comment by gokcehan** [comment] 2017-03-07 14:53
And also if you change a file with a shell command (e.g. vim) old file preview persists afterwards.

I haven't got a chance to clean things up yet when we added preview buffering. I will try to do these as soon as possible.

**Comment by gokcehan** [comment] 2017-04-09 15:21
Everything should work as intended now. I'm closing this issue but feel free to report here if there is still anything funky.

**Closed by gokcehan** 2017-04-09 15:21 UTC
