### ISSUE TITLE
Can't use uppercase shortcut for dir change

### ISSUE THREAD

**Issue by AndreaHasani** [gokcehan/lf#86] opened 2017-06-09 22:17 UTC
I don't know If I'm doing something wrong but I'm not able to assign lowercase letter follow by an uppercase one as shortcut to change directory.
For example I want to map this to Documents.
map gD cd /home/xxx/Documents

**Comment by gokcehan** [comment] 2017-10-30 21:26
@AndreaHasani I'm closing this issue as I can't reproduce it. Feel free to add a comment if you have some feedback.

**Closed by gokcehan** 2017-10-30 21:26 UTC
Labels: bug
