### ISSUE TITLE
Keyboard not working on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [gokcehan/lf#392] opened 2020-06-24 16:48 UTC
When lf starts it shows the initial screen but then it doesn't respond to keyboard clicks.

Also see user experiences here: https://forums.freebsd.org/threads/terminal-file-manager-misc-lf-not-operational.75804/#post-466229

**Comment by gokcehan** [comment] 2020-06-27 19:16
@yurivict I have read the thread. I don't think socket error is related to this. On the first launch, client starts a server process and tries to reconnect with increasing intervals when the first one fails. I'm not sure how shell choice could make a difference either if you don't have a user config file yet.

We have had some termbox related issues in OpenBSD reported in #139 which may be related to this. Did you compile from the source? If so, can you try running one of the demo programs that comes with termbox to see if it's termbox related?

    go run ~/go/src/github.com/doronbehar/termbox-go/_demos/keyboard.go

**Comment by flw-cn** [comment] 2020-07-09 10:24
I ran into this issue as well, so I did some research.
Ultimately it was determined that the cause was a bug(nsf/termbox-go#218) fixed in nsf/termbox-go@58d4fcbc that wasn't pull into doronbehar/termbox-go.

I tried to change the dependency from doronbehar/termbox-go to nsf/termbox-go, the problem is solved.
But I don't know why lf should depend on doronbehar/termbox-go, so this change on my fork(flw-cn/lf@805bee48) is only For reference.
I expect @gokcehan to actually fix the problem eventually.

**Comment by yurivict** [comment] 2020-07-09 15:25
Fixed in r541755.

**Comment by flw-cn** [comment] 2020-07-09 16:01
I noticed that @yurivict  has already provided a patch to fix the problem. This does seem to work. But I would also like to fix this issue at the origin to ensure `go get` user experience. @gokcehan 

So, @yurivict can you reopen this issue?

Thank you!

**Comment by yurivict** [comment] 2020-07-09 16:07
Reopened.

**Comment by gokcehan** [comment] 2020-07-10 15:01
@flw-cn @yurivict @Jehops @uqs Thank you all for investigating and fixing the issue. We switched to our own fork of termbox-go as part of #138 since nsf was not interested in patches. I didn't realize our fork was not up to date.

@doronbehar Can you pull the missing commits from nsf fork?

FYI, we eventually want to switch from termbox-go to tcell, which is tracked in #302 .

**Comment by doronbehar** [comment] 2020-07-11 07:26
<details><summary>You are correct.</summary>

```
$ git diff doronbehar/master nsf/master
diff --git c/README.md w/README.md
index 5ef4758..a54d218 100644
--- c/README.md
+++ w/README.md
@@ -45,6 +45,7 @@ There are also some interesting projects using termbox-go:
  - [pexpo](https://github.com/nnao45/pexpo) is a terminal sending ping tool written in Go.
  - [jid](https://github.com/simeji/jid) is an interactive JSON drill down tool using filtering queries like jq.
  - [nonograminGo](https://github.com/N0RM4L15T/nonograminGo) is a nonogram(aka. picross) in Go
+ - [tower-of-go](https://github.com/kjirou/tower-of-go) is a tiny maze game that runs on the terminal.
 
 ### API reference
 [godoc.org/github.com/nsf/termbox-go](http://godoc.org/github.com/nsf/termbox-go)
diff --git c/api.go w/api.go
index 92e3a44..3adfdc6 100644
--- c/api.go
+++ w/api.go
@@ -2,13 +2,16 @@
 
 package termbox
 
-import "github.com/mattn/go-runewidth"
-import "fmt"
-import "os"
-import "os/signal"
-import "syscall"
-import "runtime"
-import "time"
+import (
+	"fmt"
+	"os"
+	"os/signal"
+	"runtime"
+	"syscall"
+	"time"
+
+	"github.com/mattn/go-runewidth"
+)
 
 // public API
 
@@ -24,7 +27,7 @@ import "time"
 func Init() error {
 	var err error
 
-	if runtime.GOOS == "openbsd" {
+	if runtime.GOOS == "openbsd" || runtime.GOOS == "freebsd" {
 		out, err = os.OpenFile("/dev/tty", os.O_RDWR, 0)
 		if err != nil {
 			return err
diff --git c/termbox_windows.go w/termbox_windows.go
index 22e0f9e..d46eb04 100644
--- c/termbox_windows.go
+++ w/termbox_windows.go
@@ -771,7 +771,11 @@ func key_event_record_to_event(r *key_event_record) (Event, bool) {
 		case vk_tab:
 			e.Key = KeyTab
 		case vk_enter:
-			e.Key = KeyEnter
+			if ctrlpressed {
+				e.Key = KeyCtrlJ
+			} else {
+				e.Key = KeyEnter
+			}
 		case vk_esc:
 			switch {
 			case input_mode&InputEsc != 0:
```

</details>

See https://github.com/gokcehan/lf/pull/404 .

**Closed** 2020-07-11 19:28 UTC
Labels: bug
