### ISSUE TITLE
the r29 version , the 'map G bottom' seting not working

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1239] opened 2023-05-12 03:37 UTC
![image](https://github.com/gokcehan/lf/assets/87791643/989dde94-2179-4988-a68d-04dccf995b95)

**Comment by joelim-work** [comment] 2023-05-12 04:04
Thanks for reporting, I can replicate just by typing `:bottom` into the command line.

Previously the `bottom` command would just unconditionally move to the bottom, but after b5c83db it allows for a count variable to specify moving to a specific line. For example, pressing <kbd>3G</kbd> means to move to the third line. The default <kbd>G</kbd> keybinding uses a count of 0 so it should still work, but not if you remap it manually.

The problem is that by default commands are parsed with a count of 1: https://github.com/gokcehan/lf/blob/f04401ba4d43f21a084e603a52cf20f80b0c437d/parse.go#L221-L231

This usually works, but I guess `bottom` would have to be treated differently.

**Comment by joelim-work** [comment] 2023-05-12 04:21
@newyorkthink I have submitted a PR to fix this, you are welcome to try out that patch. Otherwise in the meantime I suggest you comment out the `map G bottom` line since that is the default (I think it's rare for anyone to remap this to something else).

**Closed** 2023-05-13 13:58 UTC
