### ISSUE TITLE
Zombie process when terminal window is closed

### ISSUE THREAD

**Issue by aduros** [gokcehan/lf#485] opened 2020-10-15 19:50 UTC
When I close an xterm window running lf, the lf client process (not just the -server) stays running and only responds to kill -9. Quitting lf by using :quit doesn't have this problem.

Thanks :) Let me know if I can provide any more info to repro.

**Comment by gokcehan** [comment] 2020-10-17 20:14
@aduros Thanks for reporting. I can reproduce this on my machine. This was first fixed in #305. It looks like it was regressed somewhere between r16 and r17, most likely due to tcell port.

**Comment by gokcehan** [comment] 2020-10-20 21:33
@aduros This should now work as expected in master. Closing this issue. Feel free to leave further comments if the issue persists.

**Closed by gokcehan** 2020-10-20 21:33 UTC
Labels: bug
