### ISSUE TITLE
lf terminal history is no longer clean

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#607] opened 2021-04-10 02:53 UTC
I recently upgraded my lf and I'm finding that now whenever I run a subcommand the entire screen of lf output is still rendered in my terminal history (for example if I scroll up I can see a snapshot of what lf looked like before running the command). This makes inspecting any stderr or debugging faulty commands with lf really difficult because in my case lf overwrites the stderr everytime it retakes control. Is there any way to go back to the previous behaviour where if you exit lf it basically acts as if lf was never run and scrolling back you only see the output from any subcommands that lf ended up running?

## Reproduction Instructions
Config:

```
map I !true

cmd say-hello ${{
    echo "Hello world"
}}
```

1. Start `lf`
2. Enter `:say-hello<return>`
3. Enter `!true`
4. Scroll up and down.

### Expected
I can see the output hello from the previous command and scrolling back I don't see any hint of lf being run.

### Actual
I can't see output from any previous commands and there multiple snapshots of lfs previous state in the backlog.

## Version Information
- `lf -version`: r21
- `uname -a`: `Linux mk-desktop 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux`

**Comment by gokcehan** [comment] 2021-04-13 21:47
@mohkale I think this is a duplicate of #586 which is now fixed in r22 release. Closing this issue.

**Closed by gokcehan** 2021-04-13 21:47 UTC
