### ISSUE TITLE
Feature request: cd on exit

### ISSUE THREAD

**Issue by jocap** [gokcehan/lf#140] opened 2019-02-18 22:29 UTC
I think it would be nice to have the parent shell cd to the directory opened in lf on exit, similarly to what [fff] does.

[fff]: https://github.com/dylanaraps/fff/

There would be two components to this feature:

1. Echoing the open directory to stdout on exit
2. Creating a second command, 'cancel', which would exit with error without echoing the directory

(The 'cancel' command would make it possible to quit lf without having the shell cd to the opened directory.)

fff achieves step 1 by writing to a file on disk, but I don't this really is necessary. Instead of to stdout, the user interface can be printed directly to the tty, leaving room in stdout for echoing the directory.

Thoughts?

**Comment by occivink** [comment] 2019-02-18 22:46
It's already possible, you can find some scripts (for [posix shell](https://github.com/gokcehan/lf/blob/master/etc/lfcd.sh) or [fish](https://github.com/gokcehan/lf/blob/master/etc/lfcd.sh)) in the repo for doing just that

**Comment by jocap** [comment] 2019-02-19 07:36
Aha, thank you. But that solution doesn’t seem to cover step 2?

**Comment by gokcehan** [comment] 2019-02-19 12:19
@jocap We have shell commands which pauses the ui and use the underlying stdin/stdout/stderr for input and output so things can get confusing if we use stdout instead of a separate file though I haven't actually tried this. We don't have a separate command implemented for step 2 but maybe someone may have already come up with a clever solution that I haven't considered. My workaround for this case is simply to go back with `cd -` after exiting if necessary.

**Comment by occivink** [comment] 2019-02-19 12:30
I think a solution would be for `quit` to take an optional return code, and in the wrapper script you would only `cd` if `lf` returned 0.

**Comment by gokcehan** [comment] 2019-02-19 12:50
@occivink That could work I guess. We can also add a separate command for this. In the meantime, I also thought about a workaround using marks as follows:

    push m-
    map Q push '-q

@jocap You can put this in your `lfrc` file. First command marks the inital directory with `-` key, and the second command assigns `Q` key to load `-` mark first before quitting.

**Comment by jocap** [comment] 2019-02-19 18:12
Olivier Perret wrote:
> I think a solution would be for `quit` to take an optional return code, and in the wrapper script you would only `cd` if `lf` returned 0.

This is a good idea.

gokcehan wrote:
> @jocap You can put this in your `lfrc` file. First command marks the inital directory with `-` key, and the second command assigns `Q` key to load `-` mark first before quitting.

And this is a nice workaround.  Thank you!

**Comment by nostdm** [comment] 2019-04-28 16:17
These solutions here are pretty neat. 

I added the following to my `.zshrc`: 
I found it useful to name the function the same way as the `lf` binary and call the binary directly using the full path `/usr/bin/lf`:

```
lf () {
    tmp="$(mktemp)"
    /usr/bin/lf --last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}
```

Also added this to my `lfrc` to use `Q` when returning to the original directory:
```
push m-
map Q push '-q
```

Thanks!

**Comment by gokcehan** [comment] 2019-04-29 08:34
@nostdm You can also use `command lf` instead of `/usr/bin/lf` so you don't have to hardcode the full path.

**Comment by Glench** [comment] 2020-03-18 17:40
Love that this feature is up for discussion. Any chance of it coming in a release?

**Comment by gokcehan** [comment] 2020-03-18 21:27
@Glench The workaround already seems to work so I don't think there is anything else we need to do about this. We should probably close this issue.

**Comment by Glench** [comment] 2020-03-18 21:41
So the workaround is this?
```push m-
map Q push '-q```
and it lets you execute the cd command to the current directory displayed in `lf`?
If so, where is the lfrc file go?

**Comment by gokcehan** [comment] 2020-03-18 21:57
@Glench You also need `push m-` command so it saves the current directory in `-` mark on startup. Please see the documentation about where the lfrc file go.

**Comment by Glench** [comment] 2020-03-18 22:11
Oh sorry, mispaste. But even with that I don't see the expected behavior of leaving my shell `cd`ed to the last directory I was in in `lf` when I do `Q`. In fact, it says `mark-load: no such mark`.

```
$ cat ~/.config/lf/lfrc
push m-
map Q push '-q
```

**Comment by gokcehan** [comment] 2020-03-20 18:15
@Glench Just to be clear, if you want to change to the last directory, you need to be using the script provided in `/etc/lfcd.sh`. If you want to cancel changing directory when using `lfcd` you can use that mapping. I have tried it again and it is working as intended. If you're still having trouble feel free to leave further information.

**Comment by freed00m** [comment] 2020-03-21 17:53
@gokcehan I get random promts for `mark-save:` on startup with that tweak
 
```
# For exiting in the original direcotry lf started from
push m-
map Q push '-q
```

They are appear randomly, most noticably while launching `lf` right after exiting one in the same shell.

**Comment by ranebrown** [comment] 2020-03-24 15:08
I'm also having issues with the suggested mapping but it isn't related to `mark-save:`. When I press `Q` I get `mark-load: no such mark` even though I can see the `-` mark saved when just pressing `'`.

**Comment by Glench** [comment] 2020-03-25 17:29
okay, I got *something* working with the `/etc/lfcd.sh` script in this repo but it's not what I wanted.

To be clear, what I was hoping for was the normal behavior of the `lf` program but a keyboard shortcut that does the cd on exit. So I would type `lf` then go to a different directory. If I type `q` then it just quits as normal and doesn't change directory but if I type `Q` (or `cd` or something) then it quits and changes the current working directory.

Is this possible currently or a planned feature?

**Comment by gokcehan** [comment] 2020-04-01 15:07
@Glench You can play around with the mappings to get what you want. For example:

    push m-
    map q push '-q
    map Q quit

You can also define commands for this purpose.

@freed00m @ranebrown I have been able to reproduce it once but I can't do it again. It seems like a random bug. I'm marking this issue as a bug in the meantime.

**Comment by ranebrown** [comment] 2020-04-01 15:34
Seems like it might be related to using `-`.  Using a character like `w` seems to work. (I think `map q push '-q` creates a recursive mapping, didn't work for me at least). Using the below there is a delay when exiting using `q` for some reason.

```
push mw
map q push 'w:quit<enter>
map Q push :quit<enter>
```

**Comment by gokcehan** [comment] 2020-04-01 16:16
@ranebrown I wrote the above example from head head and you're right, there is a recursive mapping, so `q` should be as in your example. I don't think it is needed for `Q` though.

Regarding the bug, I still can't produce it using `w` mark so I'm not sure if it's related.

**Comment by gokcehan** [comment] 2020-10-20 21:43
There was a race condition with `push` commands which was most likely the reason for this bug and it is fixed in r17 release. Closing this issue now. Feel free to report back if the issue persists.

**Closed by gokcehan** 2020-10-20 21:43 UTC
Labels: bug

**Comment by ranebrown** [comment] 2020-10-20 23:41
Delay issues seems to be fixed. Thanks!

**Comment by Lodifice** [comment] 2022-04-07 11:57
> @Glench You can play around with the mappings to get what you want. For example:
> 
> ```
> push m-
> map q push '-q
> map Q quit
> ```
> 

This is currently broken, as marks are written to disk immediately (and appear to be automatically sourced after the marks file changes). So if I open two instances of lf from different directories, then, when I press q in the first one, it will change to the directory the second instance was launched in.

**Comment by ilyagr** [comment] 2022-08-27 05:37
The `push m-` trick is very nice 90% of the time. Unfortunately, it doesn't work if you start lf with a path, i.e. `lf some/other/directory`. Then, pressing `q` would put you into `some/other/directory`, not where you started.

So, I think a better solution is still needed.

**Comment by ilyagr** [comment] 2022-08-27 05:41
I also tried replacing `'-` with `cd $OLDPWD` , but it doesn't work. `cd $OLDPWD` is an lf command, not a shell command, so it doesn't see the environment variable.

**Comment by ilyagr** [comment] 2022-08-27 06:56
I think I solved the puzzle:

```
map q %{{
  lf -remote "send $id :cd $OLDPWD; quit"
}}
map Q quit
```

**Comment by Lodifice** [comment] 2022-08-30 08:33
Good @ilyagr this also solves the problem I had when running multiple instances of lf simultaneously. In the meantime I worked around the problem by having lf write the directory the parent shell should cd into to a custom file descriptor, but now I can use --last-dir-path again.

**Comment by ranebrown** [comment] 2022-09-05 13:17
Is there some additional step to have OLDPWD defined? I get this error: `--: line 2: OLDPWD: unbound variable`

**Comment by Lodifice** [comment] 2022-09-06 07:30
> Is there some additional step to have OLDPWD defined? I get this error: `--: line 2: OLDPWD: unbound variable`

`$OLDPWD` is a shell variable, so make sure to use it in a shell context like @ilyagr.
What shell do you use? It works for me with Bash.

**Comment by ranebrown** [comment] 2022-09-06 12:20
I use bash. It seems to be unset when a new shell is opened. Even if I ensure it is defined in the shell where I spawn lf it seems to not be set within lf. I'm guessing lf is using a fresh shell and not inheriting that variable.

**Comment by ilyagr** [comment] 2022-09-11 02:43
Perhaps you are using really old version of lf (before r22, where [this seems to have been introduced](https://github.com/gokcehan/lf/commit/4601e74d666ee1f5b41dd120587e131d0e546e9d)), @ranebrown?

If you enter `!echo $OLDPWD<enter>` in lf, you should see the value of the shell variable.

**Comment by ranebrown** [comment] 2022-09-11 09:53
I'm on version 27. I get the same unbound variable error with the echo.

**Comment by harishnkr** [comment] 2022-09-23 15:35
The workaround seems fine but you have to type lfcd instead of lf. Adding alias lf to lfcd creates an error

>lf:2: maximum nested function level reached; increase FUNCNEST?

Maybe increasing FUNCNEST may fix the issue, but is there a workaround to this workaround?

**Comment by ilyagr** [comment] 2022-09-23 19:14
@harishnkr You are getting an issue with infinite recursion. To solve it, change the `lf -last-dir-path=$tmp $argv` line in `lfcd.sh` to `command lf -last-dir-path=$tmp $argv` or `/path/to/lf -last-dir-path=$tmp $argv`. Afterwards, either of your solutions should work.

**Comment by Lodifice** [comment] 2022-10-11 08:48
Interesting, as processes spawned by shells inherit the environment
variables of their parents.  Nevertheless, I would use a shell function
for starting lf like the `lfcd` from above.

**Comment by harishnkr** [comment] 2022-10-14 06:14
@ilyagr Thanks! It worked without a problem.
