### ISSUE TITLE
Directory specific options

### ISSUE THREAD

**Issue by psnszsn** [gokcehan/lf#171] opened 2019-05-24 08:13 UTC
Sorry if this has been discussed before, but i could not find any reference to it.

Is there a way to set directory specific options?
Examples: 
- sort the downloads directory by date
- show hidden files in specific directories

In ranger this is accomplished with `setlocal path=/path options`.

**Comment by gokcehan** [comment] 2019-05-24 14:34
@psnszsn I think this is a duplicate of #117. We currently do not have a way to set local settings for directories.

**Comment by JurisMajors** [comment] 2019-06-20 21:05
Are there any plans for this?

I don't know how this would get parsed within a config, however, is it any more complicated than just having a mapping from path to command (string to string) and then executing this command whenever you cd in a directory that is in this mapping as a key?

**Comment by gokcehan** [comment] 2019-06-21 12:25
@JurisMajors I haven't given this much thought but I'm guessing this is not trivial to implement. We need to add a new keyword such as `setlocal` to the parser, keep these special configurations within a map, and use these whenever we use a value of an option. We probably need to touch almost everywhere in the codebase to implement this. I'm not saying it is impossible but it is not quite easy either.

**Closed** 2020-07-08 02:52 UTC
Labels: duplicate

**Comment by reg-iii** [comment] 2020-07-28 13:44
Any chance we'll ever see this? It would be nice to display the contents in my home folder in alphabetical order and my downloads in reverse chronological order...

**Comment by gokcehan** [comment] 2020-08-01 00:44
@reg-iii The ratio of requests/contributors is still pretty high. I would say your best bet is to work on this yourself, and optionally send a PR when you feel confident about it.

If anyone is interested in working on this, it seems that everything mentioned here is about sorting (including `hidden`, `dirfirst`, `reverse`). We already have a representation of this in the code as `sortType`. Every `dir` has a `sortType` and we check this value against `gOpts.sortType` whenever we load the directory. There aren't many of these checks.

I guess the more tricky part is to add a new type to the parser and the evaluator. There should be a new keyword in the lexer (i.e. `setlocal`), a new rule in the parser (i.e. `SetLocalExpr  = 'setlocal' <dir> <opt> <val> ';'`), and the corresponding `func (e *setLocalExpr) eval(app *app, args []string)` implementation in the evaluator.
