### ISSUE TITLE
Switch from Freenode to Libera.Chat

### ISSUE THREAD

**Issue by JPcode05** [gokcehan/lf#712] opened 2021-10-29 15:56 UTC
I accidentally hit enter on just the title. Now I'm editing to compose my real message. Sorry guys.

But back in May, there was a hostile takeover of Freenode, and everyone moved their IRC channels to Libera.Chat. I just now went to #lf on Libera Chat, and if you're having trouble reserving it, remember my IRC nick is `jamesp`. Please comment if you have any questions.

**Comment by gokcehan** [comment] 2021-12-02 14:55
I was told that freenode went off completely yesterday. I'm currently trying to register a channel in libera.chat. I contacted a staff member and currently waiting for an answer. I'll keep this issue updated. I'm also pinning this issue for visibility.

@JPcode05 Are you like a staff member there in libera.chat? If so, maybe you can also help with registration.

**Comment by gokcehan** [comment] 2021-12-02 15:01
By the way, sorry for neglecting this issue for so long. I'm quite busy with work lately so I wasn't active in our issues. Also, I wasn't aware the situtation with freenode was that serious.

**Comment by JPcode05** [comment] 2021-12-02 20:48
> I was told that freenode went off completely yesterday. I'm currently trying to register a channel in libera.chat. I contacted a staff member and currently waiting for an answer. I'll keep this issue updated. I'm also pinning this issue for visibility.

Wow, I didn't know that. And if you go to freenode.net as of today it now looks like a mini-version of Reddit (powered by [Throat](https://github.com/Phuks-co/throat)).
 
> @JPcode05 Are you like a staff member there in libera.chat? If so, maybe you can also help with registration.

No, I'm not. But [here's how to register a channel](https://libera.chat/chanreg/).

If that doesn't work, I could register the channel as I'm the only member of the channel, then figure out how to transfer the ownership to you.

**Comment by gokcehan** [comment] 2021-12-02 21:06
@JPcode05 I can also try registering with my username but I think maybe they require registering the project to a namespace before registering the channel. I have sent the staff an email with the requested information as described in the page you linked. It might be better to wait for an answer before doing anything else. They might be busy with several requests if freenode went off yesterday.

**Comment by JPcode05** [comment] 2021-12-03 04:45
Then you can use ##lf on libera.chat instead while you wait. Count it as a semi-unofficial channel until you get #lf.

**Comment by gokcehan** [comment] 2021-12-03 11:35
@JPcode05 Actually, they registered the project yesterday and I registered the channel `#lf` so people can start using it. I have changed the link in the readme now. There was an issue with IRC integration on matrix side which I'm still working on so matrix and irc channels are not bridged yet.

**Comment by gokcehan** [comment] 2021-12-03 21:55
I still could not bridge the IRC channel with matrix so channels are still separate for the while and I removed the IRC bridge notice from the readme. It seems that the issue is already reported in https://github.com/matrix-org/matrix-appservice-irc/issues/1496

**Comment by gokcehan** [comment] 2022-02-12 10:03
IRC bridge is working again now with Libera. Closing this issue now.

**Closed as completed by gokcehan** 2022-02-12 10:03 UTC
Labels: bug

**Comment by gokcehan** [comment] 2022-02-12 10:18
Hmm, my messages in matrix channel did not show up on IRC. Is this working as intended? I don't remember how it used to work before. Feel free to leave a comment if there's still an issue with the bridge.
