### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by ipstone** [gokcehan/lf#12] opened 2016-08-31 13:16 UTC
I am looking for a cross-platform file manager written in go, might this work on Windows machine?

**Comment by gokcehan** [comment] 2016-08-31 13:51
@ipstone Short answer is currently it doesn't work unfortunately but it might in the future if there is enough interest.

I tried to run it on windows natively a while back ago. It was somewhat showing the ui but it wasn't really usable at all. I'm aware of following issues that needs to be dealt with:

- Waiting commands uses a posix shell command to do the waiting
- File delete/yank/paste uses `cp` and `mv` respectively
- There might be some hardcoded unix path seperators (`/`) in the code
- Server/Client communication is implemented with unix domain sockets

On a side note, with the Windows 10 anniversary update last month Windows Subsystem for Linux (WSL) has become available to everyone as an optional beta feature. Ideally it would be much easier to run it on WSL. However the last time I tried, it was crashing on startup. In fact all termbox applications was crashing. The problem is most likely due to some signals used in termbox initialization. As far as I know there are some issues with other Go applications as well. If these issues are solved at some point, WSL may also become an option.

Let's keep this issue open.

**Comment by 5k3105** [comment] 2016-09-28 22:30
It seems to work with [cmder ](http://cmder.net/) on windows.

**Comment by gokcehan** [comment] 2016-09-29 09:05
@5k3105 It works in `cmd.exe` but there are still missing features such as copying files and running commands. I have never heard `cmder` though. I will give it a try, thanks.

**Comment by gokcehan** [comment] 2017-10-30 20:52
I have been working on the windows support for a while. All the things mentioned here before are now fixed. There are still some minor issues with the ui on the termbox-go library which I may try to tackle at some point. I have added `lfcd` scripts for `cmd.exe` and `powershell` to the repository. We may also prepare different config file examples for windows, particulary for a `trash` or `remove` command. I'm closing this issue now as it has become too generic.

Also, I realized go language does not support cygwin officially, and likely WSL too, so those platforms may not be an option unless things are changed.

**Closed by gokcehan** 2017-10-30 20:52 UTC
Labels: question
