### ISSUE TITLE
Sixel preview doesn't work after upgrading `chafa` to version 1.14

### ISSUE THREAD

**Issue by Steven79203** [gokcehan/lf#1582] opened 2024-01-20 12:00 UTC
Just recently I noticed that my the sixel image preview stopped working. Instead of showing the image it just shows a bunch of characters on the preview space. Don't know exactly where is the problem since chafa is capable of showing the image in the terminal if I open it out of the file manager. Other previewers like ctpv also show the same problem. Both compiled and the packaged version that comes with Arch behaves the same way.  

![screenshot_20-01-2024_08-56-30](https://github.com/gokcehan/lf/assets/75397801/d519e53a-0abf-475d-8905-590344829337)

Details: 
System - Arch Linux 
Kernel - 6.7.0-arch3-1 
Terminal emulator -  foot version: 1.16.2 +pgo +ime +graphemes -assertions
lf version - lf 31-1 Arch package

**Comment by joelim-work** [comment] 2024-01-21 03:10
The discussion is already taking place in https://github.com/hpjansson/chafa/issues/185 so I'll close this since it's a duplicate.

**Comment by joelim-work** [comment] 2024-01-22 02:17
Starting from [version 1.14.0](https://github.com/hpjansson/chafa/releases/tag/1.14.0), `chafa` now disables polite mode by default, which means additional terminal sequences are prepended to the previewer output, causing `lf` to not treat it as sixel data. 

To fix this, please use the `--polite on` option when using `chafa`.

I will keep this issue pinned for a while.

**Comment by rxmmah** [comment] 2024-02-14 03:01
i am using ctpv as the previewer in lf, i did `set sixel true` but photos are showing bad.
how can i pass --polite on in my case?

**Comment by joelim-work** [comment] 2024-05-20 11:12
I think this has been pinned long enough, and everyone interested is now aware that the issue is actually with `chafa`/`ctpv` and not with `lf`.

Closing now.

**Closed by joelim-work** 2024-05-20 11:12 UTC
