### ISSUE TITLE
Handling of PWD in Windows

### ISSUE THREAD

**Issue by Nikostratos** [gokcehan/lf#740] opened 2022-01-26 10:15 UTC
1st: Thank so much for providing this awesome file-manager - also for Windows.
This is a great win!!

In Windows there is a strange behaviour with pwd-variable.
Seems like a bug?!

shell is cmd

`!echo %f%`
`"C:\Users\dude\Documents\file.pdf"`
Quotes are added as expected.

`!echo %PWD%`
`C:\Users\dude\Documents`
With PWD the quotes are missing.

`!echo "%PWD%"`
` \"C:\Users\dude\Documents\"`
Now quotes are escaped, which doesn't work for the cmd-scripts.

**Comment by gokcehan** [comment] 2022-01-26 14:26
@Nikostratos Thanks for reporting. `PWD` was added in #591 and later added on windows in 229b7b1adee79282931011a83ee781bf1e018ccc but it looks like I forgot to quote it properly. I have now changed the code to quote `PWD` similarly to `f` and others so it should work as intended. Closing this issue now. Feel free to reopen if the issue persists.

**Closed by gokcehan** 2022-01-26 14:26 UTC
Labels: bug
