### ISSUE TITLE
Can't deal with filenames with newlines

### ISSUE THREAD

**Issue by avidseeker** [gokcehan/lf#1494] opened 2023-11-09 19:32 UTC
Create a filename with a new line in its name:
```sh
$ touch new$'\n'line
```
then try to move it or delete it or use any operation on it using Lf.

I know... why would someone do such thing? I too think that this shouldn't be allowed. But filesystems, unfortunately allow it. I'm mentioning this issue in case someone specifically crafted such file to cause trouble. E.g: the file was extracted from a possibly malicious zip.

**Comment by joelim-work** [comment] 2023-11-10 00:33
Duplicate of #1114

**Closed** 2023-11-10 23:58 UTC
Labels: duplicate
