### ISSUE TITLE
Doesn't work inside neovim

### ISSUE THREAD

**Issue by hupfdule** [gokcehan/lf#200] opened 2019-07-12 13:33 UTC
I tried your lf.vim script to integrate `lf` as file manager inside vim, but found that this works inside vim, but not inside neovim.

It seems that neovim behaves differently than vim in respect to the tty.
When calling 

`:!lf` 

inside neovim I get:

```
2019/07/12 15:29:50 initializing termbox: open /dev/tty: no such device or address                                                                          
```

So there seems to be a problem related to `/dev/tty`

When i call

`!tty` 

in vim I get:

```
/dev/pts/30
```

in neovim I get:

```
not a tty
```

So obviously neovim behaves differently here. 

However, other tools like `ranger` or `fzf` can be called from withing vim. There must be a way to do so in neovim.

I even found [this issue for fzf](https://github.com/junegunn/fzf/issues/447) which is also about /dev/tty. So it seems fzf _is_ using /dev/tty and is still working inside neovim.

**Comment by gokcehan** [comment] 2019-07-14 14:37
@hupfdule I don't know what neovim changed to run `!` commands. As far as I know, `ranger` and `fzf` both use ncurses library, whereas we are using termbox, which can behave differently. There is a [Lf.vim](https://github.com/ptzz/lf.vim) script that you can use which I think works in neovim as well. I haven't got the chance to look at it yet. I will try to see if we can make a simple change to the script in our repo to make it work with neovim as well.

**Comment by hupfdule** [comment] 2019-07-15 07:02
@gokcehan Thanks, I didn't notice that a separate [Lf.vim](https://github.com/ptzz/lf.vim) package exists. This actually does work. That plugin differentiates between vim and neovim and runs `lf` explicitly in a terminal window for neovim. So that seems to be the solution.

Just out of curiosity I have tried to directly call `ranger` and `fzf` from within neovim and both do not work if not run in a terminal window (just with different error messages than `lf`):

```
:!ranger
Error: Must run ranger from terminal                                                                                                                        
```

```
:! fzf
inappropriate ioctl for device                                                                                                                              
```

So it just seems that the `lf.vim` provided in your repository is just a minimal version and doesn't support neovim. Since `ptzz/Lf.vim` does a bunch of other tricks to work correctly, how about removing the `lf.vim` in your repository and instead mentioning `ptzz/Lf.vim` in your README?

**Comment by gokcehan** [comment] 2019-07-15 13:33
@hupfdule I have now mentioned this plugin in the integrations wiki page. Vim script in the repo is intended for packages that only provides a simple function without any configuration options or automatic keybindings so that it can be installed automatically in a non-intrusive way. This is a similar approach taken by `fzf` as well. I'm willing to make it work in neovim as well though neovim has some questionable design choices in this regard. Using `termopen()` seems to make it spawn a `lf` process but it requires defining a callback function and I didn't feel like copy pasting file opening logic there. If anyone is familiar with neovim and wants to refactor the script in a simple way to make it work, feel free to do so. If not, I may try take a look at this later on though I don't see this a priority.

**Comment by gokcehan** [comment] 2020-07-03 23:52
I have taken a look at this again. There doesn't seem to be an easy way to make the function work in neovim. Closing this issue. Feel free to leave further comments.

**Closed by gokcehan** 2020-07-03 23:52 UTC
Labels: bug

**Comment by DanSM-5** [comment] 2024-11-07 02:29
I've found a way to make lf work in neovim without the need of extra plugins or dependencies. It has room for improvements though, it currently closes the window (if you have any split) when closed without selection but it may be used as an example as all the needed code is in a single place.

For some reason it didn't work for me in vimscript maybe related to the `on_exit` callback for termopen.

```lua
local lf = function()
  local temp = vim.fn.tempname()
  local buf = vim.api.nvim_create_buf(false, true)
  local cwd = vim.fn.expand('%:p:h')
  pcall(vim.api.nvim_set_option_value, 'filetype', 'lf_buffer', { buf = buf })

  -- Enable insert mode on open
  vim.api.nvim_create_autocmd('BufEnter', {
    buffer = buf,
    callback = function()
      vim.cmd.startinsert()
    end,
  })

  -- Open buffer in current window
  vim.api.nvim_win_set_buf(0, buf)

  -- Use to force nvim call termopen in created buffer
  vim.api.nvim_buf_call(buf, function()
    vim.fn.termopen({ 'lf', '-selection-path=' .. temp }, {
      cwd = cwd,
      on_exit = function(jobId, code, evt)
        local ok_fileredable = pcall(vim.fn.filereadable, temp)
        if not ok_fileredable then
          -- Needed to remove "[Process exited 0]"
          vim.fn.feedkeys('i')
          return
        end

        local ok_names, names = pcall(vim.fn.readfile, temp)

        if not ok_names then
          -- Needed to remove "[Process exited 0]"
          vim.fn.feedkeys('i')
          return
        end

        if #names == 0 then
          -- Needed to remove "[Process exited 0]"
          vim.fn.feedkeys('i')
          return
        end

        for i = 1, #names do
          if i == 1 then
            vim.fn.execute('edit ' .. vim.fn.fnameescape(names[i]))
          else
            vim.fn.execute('argadd ' .. vim.fn.fnameescape(names[i]))
          end
        end
      end,
    })
  end)
end

-- LF command
vim.api.nvim_create_user_command('LF', lf, { force = true, bar = true })
```

**Comment by DanSM-5** [comment] 2025-02-20 02:47
Unfortunately the `lf.vim` sample won't work in neovim until https://github.com/neovim/neovim/issues/1496 gets resolved which honestly doesn't look feasible in the near future.

That is the same root cause for the trick `:w !sudo tee %` nor working https://github.com/neovim/neovim/issues/12103.

I similar to you, refuse to use the plugin as it requires yet another dependency for something I consider should be relatively simple (and it is). So I took the time to figure out how to make it work, however due to the issues above, it is impossible to make the existing working sample for vim to work in neovim as it relies on a interactive command with `!`.

I did the sample above using lua as that was the sample code I found to run commands in a terminal buffer which seems to be the only possible workaround to run interactive commands. I am not very versed in vimscript as to try to adapt the snippet and since it was meant to be a neovim workaround, I considered leaving it as a lua snippet was ok.

It is not elegant but an if statement was all I need in my vimrc

```vim
if has('nvim')
  " override the command `LF` from lf.vim
  runtime lua/config.lua
endif
```

It may be possible  to use a terminal buffer for both vim and neovim but it isn't very simple as both apis diverge at that point. Neovim uses `termopen` and vim `term_start` and I'm unsure if it will behave the same as both terminal implementations behave different. You can try on vim `:call term_start('lf')` for a quick test and it will open `lf` in a split, still some additional work is needed to handle the file(s) selected and open them, though not sure if the extra complexity is worth here as there is an already working sample in the `lf.vim` file.

**Comment by DusanLesan** [comment] 2025-02-20 14:22
> That is the same root cause for the trick `:w !sudo tee %` nor working [neovim/neovim#12103](https://github.com/neovim/neovim/issues/12103)

That is weird. I use `:w !sudo tee %` daily in nvim without issues. Is your askpass working ok?

**Comment by DanSM-5** [comment] 2025-02-20 15:32
> Is your askpass working ok?

Are you talking about the gui password prompt or setting the SSH_ASKPASS?

Either way, none is needed for vim. You can see in the linked issue there is mention of the askpass workaround.

**Comment by DusanLesan** [comment] 2025-02-20 17:45
I meant `SUDO_ASKPASS`. I even thought it is normal to have askpass set and that it is not a workaround. It feels to me like saying seeing GUI apps requires having display server as a workaround :)

**Comment by DanSM-5** [comment] 2025-02-20 18:04
It is a workaround because it is used to avoid a known issue. Issue that is recognized in the neovim repository and tracked because it breaks default behavior of how interactive cli apps work in vim. If you have an issue with the term "workaround", feel free to go to discuss it in the linked issue where it is mentioned as a "workaround".

I don't think this is the right place to discuss about semantics.
