### ISSUE TITLE
Remote command to add icons or gutter to files

### ISSUE THREAD

**Issue by gpontesss** [gokcehan/lf#843] opened 2022-05-21 23:35 UTC
Is there any remote command available for modifying a file's icon, or adding some information beside a filename? I saw there's `info`, but that doesn't allow for custom information, does it? I'm interest in writing some extensions to visualize git file status' when inside of a repository, to have an interface to interact with git tied with a file manager, and a way of easily visualizing what has been done and staged/unstaged. I'd appreciate any help.

**Comment by joelim-work** [comment] 2024-08-14 13:34
Closing as a duplicate of #83

**Closed by joelim-work** 2024-08-14 13:34 UTC
Labels: duplicate
