### ISSUE TITLE
[BUG] Some non-ASCII characters get stuck in the preview pane 

### ISSUE THREAD

**Issue by mhdna** [gokcehan/lf#1366] opened 2023-08-02 08:16 UTC
Hello, 

Thanks for this amazing project. I use LF every day!

I think this bug is related to https://github.com/gokcehan/lf/issues/807, in which some symbols get stuck in the preview pane when I open a file containing non-ASCII characters or even when previewing it sometimes.

  
[lf_bug.webm](https://github.com/gokcehan/lf/assets/76184333/5d28745f-cd23-4c8b-8483-78c05ca2f666)

**Comment by noornee** [comment] 2023-08-05 07:25
hmm, i cant reproduce this bug.

what version of `lf` are you currently on ?
i currently use version `30` and my terminal emulator is `Alacritty`.

**Comment by mhdna** [comment] 2023-08-05 09:49
@noornee I'm on the latest r30 too, and I use Alacritty as well, though, this doesn't matter as I can reproduce it in other terminal emulators.

You can reproduce it by putting these few lines into a file, and making sure to move this file into an empty directory for the bug to be apparent
```
🤭 face with hand over mouth
🫢 face with open eyes and hand over mouth
🫣 face with peeking eye
🫡 saluting face
🤐 zipper-mouth face
🫥 dotted line face
``` 
Then run `lf --config -` to use the default barebone lf config, and navigate to that file, open it in vim for example then exit it.

Weirdly enough, this bug doesn't take place with all emoji characters for example, but with some specific emojis and other non-
ASCII characters, like the ones I provided above.

**Comment by noornee** [comment] 2023-08-05 10:25
> You can reproduce it by putting these few lines into a file, and making sure to move this file into an empty directory for the bug to be apparent

whoaa, i just followed the steps you provided and it reproduced the bug!

>Weirdly enough, this bug doesn't take place with all emoji characters for example, but with some specific emojis and other non-
ASCII characters, like the ones I provided above.

ah, true.
that was why i wasn't able to reproduce this because the bug didn't occur with the emoji characters i originally provided.

**Comment by joelim-work** [comment] 2023-08-05 13:46
It looks like the issue is coming from the [`go-runewidth`](https://github.com/mattn/go-runewidth) library, which is used to determine whether a given character is single or double width. Normally you would expect that each of those emojis in the example given above are double width, but it turns out that `runewidth.RuneWidth` returns a width of 1 for some emojis and 2 for others.

I wrote a very quick program to read in text from standard input and print the widths of each rune:

```go
package main

import (
	"bufio"
	"fmt"
	"os"

	"github.com/mattn/go-runewidth"
)

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		for _, r := range []rune(scanner.Text()) {
			fmt.Printf("%s\t%x\t%d\n", string(r), r, runewidth.RuneWidth(r))
		}
	}
}
```

I only have basic knowledge of Unicode, but if anyone is able to play around with this, and also cross-reference the results with the [table](https://github.com/mattn/go-runewidth/blob/44b7c5b4d67df8ca22917b6800c158a6d3be3560/runewidth_table.go#L23-L63) for double width characters (which I believe are scraped from https://unicode.org), that would be much appreciated.

**Comment by joelim-work** [comment] 2023-08-06 03:35
So I looked into this a bit more and at this point I think the issue is not to do with the `lf` code, but rather the [`tcell`](https://github.com/gdamore/tcell) TUI library, which also depends on [`go-runewidth`](https://github.com/mattn/go-runewidth).

I was able to reproduce this kind of issue by writing a simple program that displays user-provided text before clearing it, and inputs like `🤭x` clear properly but inputs like `🫢x` don't.

```go
package main

import (
	"os"
	"time"

	"github.com/gdamore/tcell"
	"github.com/mattn/go-runewidth"
)

func setText(screen tcell.Screen) {
	text := "hello world"
	if len(os.Args) > 1 {
		text = os.Args[1]
	}

	x := 0
	for _, r := range []rune(text) {
		screen.SetContent(x, 0, r, nil, tcell.StyleDefault)
		x += runewidth.RuneWidth(r)
	}
}

func main() {
	screen, _ := tcell.NewScreen()
	screen.Init()

	screen.Clear()
	setText(screen)
	screen.Show()
	time.Sleep(time.Second)

	screen.Clear()
	screen.Show()
	time.Sleep(time.Second)

	screen.Fini()
}
```

**Comment by noornee** [comment] 2023-08-06 10:18
> So I looked into this a bit more and at this point I think the issue is not to do with the `lf` code, but rather the [`tcell`](https://github.com/gdamore/tcell) TUI library, which also depends on [`go-runewidth`](https://github.com/mattn/go-runewidth).
>
> I was able to reproduce this kind of issue by writing a simple program that displays user-provided text before clearing it, and inputs like `🤭x` clear properly but inputs like `🫢x` don't.

wow, this is interesting!! 
great stuff you did to narrow the issue down to tcell. ^^

i suppose we are gonna have to open an issue at [`tcell`](https://github.com/gdamore/tcell) repo for this to be hopefully resolved

**Comment by joelim-work** [comment] 2023-08-06 13:26
I would appreciate it if other people confirm this issue as well - just in case it turns out to be an issue specific to my machine.

**Comment by mhdna** [comment] 2023-08-06 14:59
> I was able to reproduce this kind of issue by writing a simple program that displays user-provided text before clearing it, and inputs like `🤭x` clear properly but inputs like `🫢x` don't.

I can't claim to have experience with Go, if any at all, but after grabbing the dependencies and running your code with these specific inputs I can confirm that the behavior is exactly as you have described.

**Comment by joelim-work** [comment] 2023-08-07 02:32
OK I figured it out, actually [`tcell`](https://github.com/gdamore/tcell) also uses [`go-runewidth`](https://github.com/mattn/go-runewidth) for calculating character widths, so the issue is really with the latter.

It turns out that the tables are generated using https://github.com/mattn/go-runewidth/blob/master/script/generate.go and uses https://unicode.org/Public/13.0.0/ucd/EastAsianWidth.txt as the source (`W` means wide character). Unfortunately the spec is out of date as new characters get introduced, which results in incorrect character widths.

Someone has created a PR to fix this though by updating the version to Unicode 14.0.0: https://github.com/mattn/go-runewidth/pull/56. Although the latest version is now 15.0.0, version 14.0.0 should still fix the issue, at least for these particular set of emojis.

Anyway, until that PR gets merged, there's not much more I can do here, since the issue isn't actually to do with the `lf` code.

**Comment by mhdna** [comment] 2023-08-07 16:53
> It turns out that the tables are generated using https://github.com/mattn/go-runewidth/blob/master/script/generate.go and uses https://unicode.org/Public/13.0.0/ucd/EastAsianWidth.txt

It's really interesting the way you were able to narrow down this issue piece by piece until you found the real reason behind it.

> Someone has created a PR to fix this though by updating the version to Unicode 14.0.0: [mattn/go-runewidth#56](https://github.com/mattn/go-runewidth/pull/56).

Though, it seems that the PR you mentioned has been there forever, and the guys behind [go-runewidth](https://github.com/mattn/go-runewidth) for whatever reason aren't willing to merge it yet. 

Hopefully, they take some action to upgrade their Unicode source soon, for other repos such as this to get resolved.

Thank you brother Joe, you've done any amazing job!

**Comment by noornee** [comment] 2023-08-07 18:05
> It's really interesting the way you were able to narrow down this issue piece by piece until you found the real reason behind it.

tbh. it's amazing.

> Thank you brother Joe, you've done an amazing job!

ditto!

**Comment by joelim-work** [comment] 2024-07-23 03:39
[`go-runewidth`](https://github.com/mattn/go-runewidth) has been [updated to support Unicode 15.1.0](https://github.com/mattn/go-runewidth/commit/6ceadc68530e7bfea8cba17d6523bed32912d4fa), which is the latest version. Closing this now.

**Closed by joelim-work** 2024-07-23 03:39 UTC
