### ISSUE TITLE
/mnt or /media loading problem (lf takes 100% CPU)

### ISSUE THREAD

**Issue by pcapiod** [gokcehan/lf#453] opened 2020-08-25 11:33 UTC
Hi,

I have been using lf for the last week after using ranger for months. I really like lf and I think I will stick to it because scripts are handled much better.
Every once in a while, I am facing an issue with lf taking 100% CPU which seems to be linked to the embedded external hard drive on my laptop (see below for details).

## Expected Behavior
Running smoothly without taking 100% of the CPU, trying to load the list of external hard drive partitions.

## Actual Behavior
lf is still fast and runs smoothly but takes 100% CPU. Running a second instance of lf does the same thing. When going to the /media or /mnt folder in lf, it displays a "loading..." message but I can still navigate to my external hard drives (I can select them and see names in PWD at the top of the screen).

## Steps to Reproduce the Problem

  1. Running lf after a boot in kitty terminal within tmux. A reboot seems to solve this issue
  2. Compiling the code from scratch does not solve the issue
  3. Tried in Konsole, and same thing, takes 100% CPU.

## Specifications

  - Version: lf pre-built binaries and compiled from sources
  - Platform: KDE Neon 5.19.4, Ubuntu 20.04, KDE Frameworks 5.73
  - Subsystem: Kitty terminal within tmux

**Comment by gokcehan** [comment] 2020-08-26 22:22
@pcapiod Can you try this without a preview script (i.e. `set previewer` or just comment out the relevant line) and/or preview option disabled (i.e. `set nopreview`) to see if you still have the issue? Also maybe try disabling directory counts (i.e. `set nodircounts`)  and/or information altogether (i.e. `set info`) to see any of this helps.

**Comment by pcapiod** [comment] 2020-08-27 12:32
@gokcehan, alright, thanks. I will investigate that when it will happen again!

**Comment by pcapiod** [comment] 2020-08-31 08:54
Hi,

Ok, so it happened today and no luck with all the suggestions. Setting nopreview and set info in lfrc does not solve the issue. 
One thing that I noticed then is that the marks does not load properly (default bind set to '). It only affect the display, they are working fine. Most probably because it cannot load properly the /media/ folders ?

As well, it seems that lf does not see the /media/ folders within the software. Let's say I want to open file.pdf in /media/folder
If I do
$okular /media/ <tab>, it does not see anything. Any idea to solve this? Related to permissions maybe?

Let me know if you need more info.
Thanks for your help!

**Comment by gokcehan** [comment] 2020-08-31 13:02
When you run `$okular /media/` we just spawn a shell that calls this command and leave the rest to the command itself. Can you run `okular /media/` from your shell? Are you sure this is related to `lf`?

Did you disable preview and info before or after you hit 100% CPU? If you already hit 100% CPU, and then disabled previews, it may not do anything since you already have a preview process stuck running.

**Comment by pcapiod** [comment] 2020-08-31 13:31
Maybe I was not really clear for the first point. From the folder browser, I can navigate to `/media/`. But when typing `:cd /` + tab to see the result. I can see/access `/home/` or `/bin/` for instance, but not `/media/`. And yes I can run `okular /media/file.pdf` from my shell.

I tried both options.

**Comment by gokcehan** [comment] 2020-08-31 14:41
What is the name of the process with 100% cpu usage when this happens? (e.g. what does `top` show). In your original post, you say rebooting fixes the problem. Can't you just kill the process instead of rebooting?

Also, does your log file show anything relevant?

**Comment by pcapiod** [comment] 2020-08-31 15:02
it is `lf`. For some reason, it is not consistent. In the last 2 ou 3 days, I did not have this problem. It has occurred again this morning.
Killing the process as in stopping lf and running it again. I have tried and it is the same. The only clear thing that I can mention when this problem is occurring is the "Loading..." sentence when previewing /media/. In my /media/

Which log are you referring to?

**Comment by gokcehan** [comment] 2020-08-31 18:02
> Killing the process as in stopping lf and running it again.

Do you mean like `<C-z>` and then `fg`? What I meant was something like `killall -9 lf` if the process is unresponsive and you can't quit normally.

> Which log are you referring to?

Each client has a log file for debugging (e.g. `/tmp/lf.pcapiod.1000.log`) which can have some errors not shown in the message line. See [here](https://github.com/gokcehan/lf/wiki/Contributing#bug-reports).

> In the last 2 ou 3 days, I did not have this problem. It has occurred again this morning.

I appreciate you trying everything to help, but I can't fix an issue blindly without reproducing it myself. And if even you can't reproduce it consistently, I don't know how anyone else can reproduce it. Steps to reproduce in your original post just lists some things you tried to fix the problem. It should instead show steps that other people can follow to reproduce the issue on their machines. Also you should be more explicit about things because I'm not sure what actually you did in response to some of my questions before.

**Comment by pcapiod** [comment] 2020-08-31 18:21
The process is responsive. Just taking 100% cpu. So I could quit normally.

I will have a look at the log.

I wish I could help more and try to reproduce it each time, but I just cannot comprehend when this happens unfortunately. It is already weird enough that a simple reboot can "solve" this.
I fully understand that you need clearer steps to reproduce it.
I will try to investigate it on my side and try to report things that I can find. In the end, if this is happening only on my machine, I can deal with it by just rebooting.

**Comment by gokcehan** [comment] 2020-10-26 23:44
@pcapiod Today, I encountered this bug myself. It happens on the exFAT partition of my external drive. I tried checking the modification time of a directory on the exfat partition and it shows:

```
  File: /run/media/gokcehan/7FBF-7392/lemon/
  Size: 131072    	Blocks: 256        IO Block: 131072 directory
Device: 812h/2066d	Inode: 3256        Links: 9
Access: (0755/drwxr-xr-x)  Uid: ( 1000/gokcehan)   Gid: ( 1000/gokcehan)
Access: 1979-12-31 03:00:00.000000000 +0300
Modify: 2020-11-24 00:22:26.000000000 +0300
Change: 2020-11-24 01:53:14.000000000 +0300
 Birth: -
```

So the modification time of this directory shows about 27 days into the future.

On the `lf` side, we check the modification time of directories and compare it to the time we last read the directory to determine if the directory should be reloaded or not. Since the modification time is in the future, `lf` keeps trying to reload the directory repeatedly and locks the cpu.

So this seems to be a bug in exFAT. I found a related report for Ubuntu here:

https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1872504

It says installing `exfat-fuse` and `exfat-utils` results in the correct behavior. So I guess this is a bug in the builtin kernel implementation of exFAT. If you don't mind using the the FUSE implementation instead, you may try installing the mentioned packages.

On the lf side, I guess we can fix this by adding a check to see if the modification time is in the future or not. But that is kind of silly so I haven't made up my mind yet.

**Comment by gokcehan** [comment] 2020-11-06 16:59
@pcapiod I have now pushed a fix to avoid reloading directories with a future modification time so this issue should not occur anymore. Thanks for reporting.

**Closed by gokcehan** 2020-11-06 16:59 UTC
Labels: bug
