### ISSUE TITLE
Renaming file by just capitalizing a letter

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#343] opened 2020-04-29 00:47 UTC
Renaming a file by just capitalizing one or more of its letters causes an error. For ex if I try to rename `test` to `Test`, I get the following error

![portion_2020:04:29@02:38:47](https://user-images.githubusercontent.com/59321248/80551409-abab9c00-89c3-11ea-9bd5-378fa491cb9a.png)

**Comment by BachoSeven** [comment] 2020-04-29 01:05
I cannot reproduce this. What is your `set shell`?

**Comment by n0ibe** [comment] 2020-04-29 08:34
I have not set it, so it's the default one.

**Comment by eggeek** [comment] 2020-05-12 07:23
I got same problem. What's worse, the renamed file will disappear.
My `lf --version` is `14`, the lfrc is from the [official example](https://github.com/gokcehan/lf/wiki/Tutorial#configuration)

[![asciicast](https://asciinema.org/a/Um4ksbQlyJJRK7svbwarsN4kF.svg)](https://asciinema.org/a/Um4ksbQlyJJRK7svbwarsN4kF)

**Comment by BachoSeven** [comment] 2020-05-12 10:48
what shell and terminal are you using? I still cannot reproduce it

**Comment by shabahengam** [comment] 2020-05-12 15:58
I cannot reproduce it too.
as I know Windows and Mac are case-insensitive so maybe that cause the problem.

**Comment by eggeek** [comment] 2020-05-12 23:50
> I cannot reproduce it too.
> as I know Windows and Mac are case-insensitive so maybe that cause the problem.

Yes, I'm using macOS. 
But I also tried to set the shell by `set shell zsh`.
And the renaming is work in my command line and in LF command mode e.g. `%mv A.txt a.txt`.

The problem is that I cannot find any log (under `/tmp`), thus I don't know how the LF execute the "rename" command that causes the file to disappear.

**Comment by shabahengam** [comment] 2020-05-13 00:47
I had a similar situation but get fixed.check this issue #253 
maybe that issue is not completely fixed for other OSes.(I'm using Linux)

**Comment by BachoSeven** [comment] 2020-05-13 00:49
@eggeek I don't know anything about go, but I digged around this points in the code: [eval.go](https://github.com/gokcehan/lf/commit/bfd01e5ed86292be6df21a778268c0ace800b1e6#diff-35bd763fcb0a0c25d488e8f7efaf456eR1051) and [nav.go](https://github.com/gokcehan/lf/commit/bfd01e5ed86292be6df21a778268c0ace800b1e6#diff-cf715022ea0dc1bec94a2fdee6f87e9dR743); you can see from nav.go that there's a function called os.Rename imported from the package `os`, which you can find at https://golang.org/pkg/os/#Rename. It turns out that this function calls another rename function from either [this](https://golang.org/src/os/file_unix.go) file. There, I found the following comment which can be useful to you:
```
                // However, if the old name and new name are not the same, yet
		// they refer to the same file, it implies a case-only
		// rename on a case-insensitive filesystem, which is ok.
```
Anyways, the function then seems to call yet another Rename function, this time from syscall: on an AMD64 architecture, it should be the one in [here](https://golang.org/src/syscall/zsyscall_darwin_amd64.go) at line 1297.
So the library called for the rename operation is probably `libc_rename_trampoline`.

I still have no idea what causes the error nor the file disappearance, but hopefully this can point you in a Darwin-oriented debugging of the issue.

**Comment by gokcehan** [comment] 2020-06-03 20:56
We fixed the older issue by simply checking if the new name is the same as old in a case-sensitive way which apparently fails for case-insensitive file systems. I'm not sure what would be the easiest way to fix this without adding some platform dependent code.

@n0ibe This is an important issue we should fix as soon as possible. Thanks for reporting.

**Comment by gokcehan** [comment] 2020-06-17 02:28
I have pushed a fix for this and everything should be working fine now. Closing this issue now.

**Closed by gokcehan** 2020-06-17 02:28 UTC
Labels: bug
