### ISSUE TITLE
Open lf in given directory

### ISSUE THREAD

**Issue by TeddyDD** [gokcehan/lf#88] opened 2017-10-30 10:50 UTC
Something like `lf [params] directory` would be useful. It would allow to implement simple "new tab" behaviour (open new client in current directory)

**Comment by occivink** [comment] 2017-10-30 11:09
Dupe of #63 I believe :)

**Comment by TeddyDD** [comment] 2017-10-30 11:27
Whoops, my bad

**Comment by TeddyDD** [comment] 2017-10-30 11:27
Whoops, my bad

**Closed** 2017-10-30 11:28 UTC

**Comment by gokcehan** [comment] 2017-10-30 20:12
@TeddyDD @occivink This is now possible with the latest commit.
