### ISSUE TITLE
Big bug and Big error

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1346] opened 2023-07-14 11:53 UTC
when i scroll file ,
the lf preivew is show some error
![image](https://github.com/gokcehan/lf/assets/87791643/493172bb-ca09-4ca8-82b3-281380eccf38)
![image](https://github.com/gokcehan/lf/assets/87791643/4930ca94-c9b6-40ce-877a-42a7209a2ad6)

https://github.com/gokcehan/lf/assets/87791643/91a24ebb-2c03-4575-b5cc-05cfc723a712

**Comment by og900aero** [comment] 2023-07-15 08:40
What method used? Ueberzug or other?

**Comment by newyorkthink** [comment] 2023-07-15 10:16
> What method used? Ueberzug or other?

is lf defau preview

**Comment by Gitleptune** [comment] 2023-09-12 22:30
Could this be caused by the Chinese characters? On Windows cmd I had trouble displaying CJK characters, might be something similar happening here.

**Comment by newyorkthink** [comment] 2023-09-19 02:06
> Could this be caused by the Chinese characters? On Windows cmd I had trouble displaying CJK characters, might be something similar happening here.

yes, is chinese characters

**Comment by gokcehan** [comment] 2023-09-19 09:51
@newyorkthink Is this on Windows?

**Comment by newyorkthink** [comment] 2023-09-20 01:54
> @newyorkthink Is this on Windows?

not , this is kali linux
i use i3wm env

![image](https://github.com/gokcehan/lf/assets/87791643/2887cf8c-6a32-456d-83ea-4cedd10ec451)

**Comment by joelim-work** [comment] 2023-09-21 01:22
I highly doubt this is the default preview method as mentioned in https://github.com/gokcehan/lf/issues/1346#issuecomment-1636728552, since the preview contains colors. I think this might be the output of [`bat`](https://github.com/sharkdp/bat) actually.

Though I think this is an issue with calculating the width of certain Unicode characters, similar to #1366.

**Comment by SeeInTheDark** [comment] 2023-11-02 14:36
I just find the problem can be solved by change the terminal font to monospace font, e.g. JetBrains Mono, on Windows Terminal.

**Comment by joelim-work** [comment] 2024-07-23 03:39
[`go-runewidth`](https://github.com/mattn/go-runewidth) has been [updated to support Unicode 15.1.0](https://github.com/mattn/go-runewidth/commit/6ceadc68530e7bfea8cba17d6523bed32912d4fa), which is the latest version. Closing this now.

**Closed by joelim-work** 2024-07-23 03:39 UTC
