### ISSUE TITLE
'q' quit backgrounds the process on windows, lf.exe remains running

### ISSUE THREAD

**Issue by AddictArts** [gokcehan/lf#106] opened 2018-07-19 17:31 UTC
Cannot find a way to shutdown the process while running lf. This prevents "CMD" or powershell from closing without a nasty message that doesn't make it clear it is lf that is still running.

**Comment by gokcehan** [comment] 2018-07-19 21:36
@AddictArts Thanks for reporting this. I was wondering why my `cmd.exe` was hanging on `exit` from time to time. It never occurred to me this might be related to `lf`.

The issue is likely due to our daemon server process which is automatically started on first launch and tries to stay in the background for the subsequent runs. We are using `Cmd.Start` from `os/exec` package which may not daemonize the process properly. There was also another bug I realized a while ago on unix systems in which some clients stay connected to the server after a `quit` command which can also be related to this issue. I will investigate and try to see what we can do about this.

**Comment by gokcehan** [comment] 2018-07-22 18:15
@AddictArts It is not quite relevant to this issue but I have now added a `quit` command to the server protocol. After you use `lf` in `cmd.exe`, you can run `lf -remote "quit"` to quit the server process so `exit` will not hang afterwards, though it is probably easier just to use the X button in the corner. An alternative solution is to run `lf -server` on startup somehow as a service (i.e. task scheduler) so running `lf` inside `cmd.exe` will not launch the server process. I will see if there is an easier solution to this.

The other bug I have mentioned on unix systems turned out to be related to the first client to launch the server which usually starts faster than the server so it will not be able to connect to it. I will try to fix this as soon as possible.

**Comment by gokcehan** [comment] 2018-07-31 21:29
@AddictArts Ok so we now pass detached process flag (i.e. `8`) when starting the server process on windows as documented here:

https://docs.microsoft.com/en-us/windows/desktop/procthread/process-creation-flags

Using `exit` on `cmd.exe` or `powershell` does not hang anymore and the same server is kept running in subsequent runs. It is possible to shutdown the server using `quit` remote command as mentioned before:

    lf -remote "quit"

Closing this issue now.

**Closed by gokcehan** 2018-07-31 21:29 UTC
Labels: bug

**Comment by AddictArts** [comment] 2018-08-15 23:39
Thanks, works as advertised.
