### ISSUE TITLE
lf --command "set hidden" doesn't load properly

### ISSUE THREAD

**Issue by BachoSeven** [gokcehan/lf#338] opened 2020-04-20 14:23 UTC
Independently of setting `period 1` or not, the command
```
lf --command "set hidden"
```
does not always display hidden files correctly, at least until I move to the parent directory, after which the hidden files display:

![test](https://user-images.githubusercontent.com/55460785/79762094-916a2200-8322-11ea-9ce8-362aad71a1ba.gif)

Executing `reload` also immediately displays the missing hidden files. 

I'm using the latest release, but also tested the issue on r13, using both the st and the Terminator emulators.

**Comment by n0ibe** [comment] 2020-04-29 00:42
I'm experiencing the same behaviour on macOS running r14 and alacritty.

**Comment by LordRusk** [comment] 2020-04-29 00:56
same happens for me, arch linux + st.

**Comment by BachoSeven** [comment] 2020-04-29 00:59
I forgot to mention: I was running on Ubuntu 18.04

**Comment by gokcehan** [comment] 2020-06-03 20:32
@BachoSeven This is probably due to asynchronous loading of directories. You can set `hidden` option in the configuration. What is the use case for this?

**Comment by BachoSeven** [comment] 2020-06-03 20:38
It's actually pretty specific, I should have mentioned it earlier: I want to use the above option to `set hidden` only when launching lf from [this](https://github.com/ptzz/lf.vim) vim plugin as mentioned [here](https://github.com/ptzz/lf.vim#setting-a-custom-lf-command). In fact, I originally opened this issue [there](https://github.com/ptzz/lf.vim/issues/5) before realising it had nothing to do with the plugin itself.

**Comment by n0ibe** [comment] 2020-06-03 23:12
@gokcehan I have `set hidden` in my lfrc and I have this problem too.

**Comment by langenhagen** [comment] 2020-07-07 13:22
Similar for me, but I found something else.
I have also `set hidden` in my `lfrc`, but upon starting `lf`, the hidden files are not visible most of the time. Sometimes, they are visible. Looks flaky.

I tested with a hidden folder `.foo` and then startet `lf`. `.foo` was not visible. Quit `lf`.
Started `lf` 2nd time, `.foo` was not visible. Quit `lf`.
Started `lf` 3rd time, `.foo` was visible. Quit `lf`.
Started `lf` 4th time, `.foo` was not visible. Quit `lf`.

Moving around in `lf` reliably makes the hidden files visible, also calling `:set hidden`.

I run Ubuntu 20.04. and got `lf` via `go get`.

**Comment by gokcehan** [comment] 2020-07-08 01:32
@langenhagen Thanks for testing it out. I'm able to reproduce the bug myself. Since it's non-deterministic, I suspect it is due to async loading of directories. There are a few other bugs that I suspect due to the same reason. We might need to implement a blocking version of `load` command. This will be my top priority next time I can spare time for lf hopefully in the upcoming days.

**Comment by gokcehan** [comment] 2020-07-16 20:19
With the latest update, we now check the modification time and sorting options one last time before directories are updated. I can't reproduce the bug with either `set hidden` in the configuration file or `lf --command 'set hidden'`. Closing this issue now.

**Closed by gokcehan** 2020-07-16 20:19 UTC
Labels: bug
