### ISSUE TITLE
Using bat as previewer

### ISSUE THREAD

**Issue by hajdamak** [gokcehan/lf#234] opened 2019-09-25 09:19 UTC
I am trying to use bat as previewer. In order to make bat generate ansi escape codes even when going through pipe I use `--color always` option.
When I use `set previewer bat --color always` setting preview pane just shows regular file content as cat without any bat decorations nor colors.
When as previewer I am using following script:
```
#!/bin/sh
case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    *.pdf) pdftotext "$1" -;;
    *) bat --color always "$1" ;;
esac
```
Preview pane shows only bat decorations but color is used sparingly in just a few places in file.

Am I missing something?

**Comment by TravonteD** [comment] 2019-10-01 18:42
For bat to add colors properly it needs to know what language it's highlighting. I believe its using a generic highlight, which is why you see it used sparingly.

**Comment by thezeroalpha** [comment] 2019-10-17 06:39
I've managed to get this working by using the base16 theme provided by `bat`.

So my preview script looks like this:

```bash
bat --color=always --theme=base16 "$1"
```

It's not exactly the theme I'd want, but it works.

**Comment by doronbehar** [comment] 2019-10-26 13:16
I advice you to try out [pistol](https://github.com/doronbehar/pistol) as well. It was made for terminal file managers like Lf and Ranger.

**Comment by sharkdp** [comment] 2019-10-29 19:32
@thezeroalpha Another option is to force `bat` to use interpolated 8-bit colors (which works quite well). For this to work, you would simply need to *unset* the `COLORTERM` environment variable. This way, you can use any theme you want:
``` bash
#/bin/bash
unset COLORTERM
bat --color=always "$1"
```

**Comment by hajdamak** [comment] 2019-12-05 20:28
@sharkdp Yeap, this works great.

**Comment by gokcehan** [comment] 2019-12-15 20:08
@sharkdp Thanks for the solution.

Closing this issue now.

**Closed by gokcehan** 2019-12-15 20:08 UTC
Labels: question

**Comment by younger-1** [comment] 2020-09-17 09:25
How can I use pager in Windows/win10?
In linux, i can use `set previewer ~/.config/lf/pv.sh` 
Is there an equivalent executable file in win10?
I tried this, but failed:
file location: `C:/Users/didi/AppData/Local/lf/pv.ps1` or `%LOCALAPPDATA%/lf/pv.ps1`
```ps1
bat --color=always --theme=base16 "$1"
```

**Comment by gokcehan** [comment] 2020-09-17 20:55
@younger-1 That path is not something special. You can put it anywhere you like. You can also put it somewhere in path variable and call it with the script name without the full path.

`$1` as the argument is specific to linux shells. Does the following work:

    bat --color=always --theme=base16 $Args[0]

**Comment by aug0stus** [comment] 2020-10-13 05:37
@gokcehan 

 I put `set previewer D:\\tmp\\preview.ps1` in  my `lfrc` file, and the content of `preview.ps1` is as you've suggested.

I confirm that it does not work, and the traces from the log file are


> 2020/10/13 01:28:35 previewing file: fork/exec D:\tmp\preview.ps1: %1 is not a valid Win32 application. 
> 2020/10/13 01:28:35 loading file: read |0: file already closed

As a workaround though, you can specify a batch-like file, `set previewer D:\\tmp\\preview.cmd` and do the following.

```
bat --color=always --theme=base16 %1
``` 

seems to colorize it.

**Comment by lkhphuc** [comment] 2021-02-21 18:04
Sorry to dig this up, but I can't seem to get bat to show in the right pane previewer, but I can run bat with mapping.
I have in `lfrc`:
```
set previewer ~/dotfiles/lf/pv.sh
map i $~/dotfiles/lf/pv.sh $f | less -RX
```
and in pv.sh:
```
#/bin/bash
bat --color always "$1"
```
With this, I can press `i` in `lf` and bat output will show up, however the right-pane preview is blank. The right pane preview show up again (without syntax hightligh) if I remove `set previewer pv.sh` from `lfrc`.
Is this the expected behavior or did I mess something up?

**Comment by gokcehan** [comment] 2021-02-21 23:38
@lkhphuc Don't you need a `!` in your shebang line? (i.e. `#/bin/bash` -> `#!/bin/bash`)

**Comment by lkhphuc** [comment] 2021-02-22 00:14
Dang it. Thank you @gokcehan, stupid me.
But I wonder why does `map i ...` below works fine with the same script without shebang?

**Comment by gokcehan** [comment] 2021-02-22 02:15
@lkhphuc I'm not sure about that. Maybe shell automatically considers it a shell file when it doesn't have a shebang line since we wrap these commands as `sh -c ...`.

**Comment by gokcehan** [comment] 2021-05-20 22:00
@h3ndry I think this issue was about using `bat` as a previewer but you are probably asking about using `bat` as a pager. You can define `bat` as `PAGER` in your shell configuration file (e.g. `export PAGER=bat`) or simply redefine your pager keybinding with `bat` in your lfrc file (e.g. `map i $bat "$f"`).

**Comment by thisismygitrepo** [comment] 2022-09-12 08:08
Hi from 2022 Q4,
Can anyone please summarize the solution for windows & powershell? Documentation and solutions are heavily skewed towards linux bash.
I went through the entire thread, and read the docs. I only managed to set `bat` as a "pager", but not a proper previewer.

Solution for `bat` as "pager" on powershell:
create file `pager.ps1` with contents:
```
clear
~\AppData\Local\Microsoft\WindowsApps\bat.exe  --color=always --theme=base16 $Args[0]

Write-Host -NoNewLine 'Press any key to continue...';
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
```

lfrc keymap:  `map i $~/dotfiles/settings/lf/pager.ps1 $env:f`

`bat` as a previewer, seems a more complicated beast, the docs says its must be an executable that accepts five arguments that includes pane dimensions, I wonder how people simply say solution is a file with `bat --color=always --theme=base16`.
I'd appreciate it if a thorough powershell working example is provided.
