### ISSUE TITLE
config parser seems to be broken

### ISSUE THREAD

**Issue by ekfdhqusdfja** [gokcehan/lf#341] opened 2020-04-25 10:23 UTC
This  is a working config file:

```
map l foo
map <enter> bar

cmd foo ${{
    echo 'foo'
}} 

# Comment
cmd bar ${{
    echo 'bar'
}}
```

... but if you delete the comment, the bar function can not be found inside lf.
lf version: r14-1-gc49140a

**Comment by OliverLew** [comment] 2020-04-29 02:30
I tried your config. It looks like the space after `foo` definition is breaking the config. If you remove the space, the config works fine. This seems a flaw in the config parser.

**Comment by shabahengam** [comment] 2020-04-29 19:59
related issue #301

**Comment by gokcehan** [comment] 2020-06-03 20:35
Closing in favor of #301.

**Closed by gokcehan** 2020-06-03 20:35 UTC
Labels: duplicate

**Comment by gokcehan** [comment] 2020-07-04 01:13
I have pushed a commit to fix the scanner. This example now works as intended.
