### ISSUE TITLE
Panic: the parameter is incorrect

### ISSUE THREAD

**Issue by JavierCorralLizarraga** [gokcehan/lf#479] opened 2020-10-07 17:08 UTC
Hi, 
Recently I noticed I was using an older version of LF, the one that chocolatey installs on windows (R12) so I updated it for myself and now I run the latest version. 
But I used to do the command ":delete" on a toggled file and it'd work as expected. Now that I try to use that command it throws the error shown in the image (Its in spanish but the traduction is "panic: the parameter is incorrect").
It does work as expected on some terminal emulators I tried (Hyper and the new windows terminal) inside my machine but not for the default CMD and PowerShell and Alacritty.

![image](https://user-images.githubusercontent.com/46376887/95362365-9a7c8a80-0893-11eb-90a9-40ed72dc0a4d.png)

**Comment by tarasyarema** [comment] 2020-10-08 11:34
Hi, I tried to replicate it with the HEAD branch on a Windows 10 machine using Powershell Core (7.0.1), old Powershell and cmd.exe and had no errors. Also I tried using Alactritty. 

Maybe there's some issue with the Alacritty version?

I would try to rebuild the lf binary in case there were some package version issues.

**Comment by gokcehan** [comment] 2020-10-08 16:03
@JavierCorralLizarraga By latest version, do you mean the master branch or r16? If you built from the source, can you make sure you compiled with module-aware mode (i.e. `GO111MODULE=on`), and also maybe try one of our prebuilt binaries for r16 from the releases page?

**Comment by JavierCorralLizarraga** [comment] 2020-10-08 20:39
I am using the prebuilt binaries for R16 with extension "-amd64" (which I suppose is for the 64-bit systems)
I tried replacing it with a fresh one but the same happened, then I tried with the other binaries with extension "386" but it detected it as a virus and wouldn't let me download it.
![image](https://user-images.githubusercontent.com/46376887/95510759-09351300-097c-11eb-827c-88e51461dad4.png)

**Comment by gokcehan** [comment] 2020-10-08 22:40
@JavierCorralLizarraga Your backtrace shows it panics in a `termbox.SetCursor` function. Termbox have some resize bugs in windows which might be related, though I can't reproduce the issue on my machine. On the bright side, we have already switched to a new terminal ui library in master branch. It is strongly possible that this issue is already resolved on its own in the master. If you have go installed on your machine, you can try to build from the source to see if it works. I'm hoping to push a new release r17 this weekend, so you can also wait for the new release if you like.

That virus alert is more worrying to me, though it is likely a false positive. Binaries are directly uploaded from travis to github, and I don't see much chance of a malware infection in that workflow. I tried checking the file with virustotal:

https://www.virustotal.com/gui/file/1da57c29def541eed068eab120f3c0607a8d573ca5daefada97ae101637f4e3a/detection

A recent scan shows 6/63 detected. As far as I understand, inconsistency among antivirus programs here is a strong indication of a false positive. I have also checked previous versions r15 and r14 and they don't seem to have any problems with windows defender. So it is highly possible this will be resolved on its own as well in the next release.

**Comment by gokcehan** [comment] 2020-10-20 21:47
I have pushed a new release r17 some time ago which should likely work as intended. Closing this issue now. Feel free to report back here if the problem persists and I can reopen the issue.

**Closed by gokcehan** 2020-10-20 21:47 UTC
Labels: bug
