### ISSUE TITLE
Cursors behaviour

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#1] opened 2016-08-13 17:30 UTC
What the heck are cursor keys currently doing? It looks like this (I've kept pushing the `up` key, but it seems the same for all cursors):

![out2](https://cloud.githubusercontent.com/assets/431488/17644637/3ec7d9ae-618c-11e6-9342-c401e1f83247.gif)

I guess I'd expect them to work like `hjkl`.

**Comment by gokcehan** [comment] 2016-08-13 18:48
They are not doing anything, heh. The problem is I haven't added all the keys yet. Since arrows are not handled they try to match the possible keys starting with nothing which is then all possible keys. And it's dancing like that since iteration order of maps in Go is not deterministic. It's probably a good idea to sort the bindings list before showing.

I have now pushed two commits (bdee73bc54327aaedda0a99427a98491aaa85753 and 84cf8e12c3a5acc017871610d2d2738b7e73cec5) which should prevent the above behavior with an error message instead for unhandled keys and also adds cursor keys and assign them to hjkl by default as you said. I'm not adding all the keys yet (including function keys and ctrl keys except for ctrl-l) since a refactor is needed to handle `<` and `>` keys more gracefully and also do the rest more efficiently. Let's keep the issue open for now.

**Comment by mholt** [comment] 2016-08-14 00:14
Those two commits did the trick for me. Arrow keys work now. Thanks for the temporary fix anyway :) - awesome project!

**Comment by gokcehan** [comment] 2016-09-07 19:50
I have added all possible keys a while back ago. Hopefully I didn't break anything regarding this issue in the meantime. Closing this issue now.

**Closed by gokcehan** 2016-09-07 19:50 UTC
