### ISSUE TITLE
The reload command not working automatically

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1301] opened 2023-06-12 10:58 UTC
I used the new Debian 12, and I try lf file manager again:

I noticed that the reload command does not work automatically when I copy, move or delete files. I guess it doesn't work in all other cases either. If I enter it manually, it refreshes the contents of the window.

**Comment by og900aero** [comment] 2023-06-12 11:52
I try more, and the problem only persist, when I copy, move, delete to the mountable device, like usb pendrive.

**Comment by azinsharaf** [comment] 2023-06-20 17:38
same here, I have to refresh it manually (ctrl+r)
Windows 11 Pro

**Comment by gokcehan** [comment] 2023-07-03 18:29
@og900aero @azinsharaf We use modification times to trigger reloads when required. Some filesystems do not update modification times to reduce disk writes. If that's the case, I'm afraid it is currently considered working as intended and you need manual reloads.

**Comment by azinsharaf** [comment] 2023-07-03 22:31
in my case i have a python script that creates a new folder and generates some files inside the folder. isn't it being considered as a simple file system action?

**Comment by gokcehan** [comment] 2023-07-04 09:35
@azinsharaf I'm not sure if I understood what you meant but we don't have a mechanism to detect file system actions in your commands.

**Comment by joelim-work** [comment] 2023-07-04 10:15
You can also try the `period` option, which can poll for updates to the filesystem.

**Comment by og900aero** [comment] 2023-07-04 13:20
> You can also try the `period` option, which can poll for updates to the filesystem.

I try period. Set period 3 in lf.rc. Then I browse pendrive, and delete some files, and waiting 3 seconds, but doesnt reload automatically after 3 seconds.

**Comment by joelim-work** [comment] 2023-07-04 16:07
@og900aero The `period` option also works based on modification times, so for your case it won't help. I think you'll have to troubleshoot by looking at the modification times of the files on your pendrive.

I was actually responding to @azinsharaf's issue, which I think is different. The `period` option is useful for picking up changes to the filesystem from *external* processes outside of `lf`, which was why I suggested it. Sorry for the confusion.

**Comment by joelim-work** [comment] 2024-06-22 06:27
Adding the `watch` option in #1667 should help with automatic `reload` problems, closing this issue.

**Closed** 2024-06-22 06:29 UTC
