### ISSUE TITLE
Moving mouse after using scroll wheel bound to up or down skips through directories

### ISSUE THREAD

**Issue by ghost** [gokcehan/lf#860] opened 2022-06-27 22:43 UTC
Description: When using "map <m-up> up" and/or "map <m-down>", If you scroll up or down, and then move your mouse, it will use your mouse cursor movements to move through the current directory.

Steps to reproduce:
1. Map scroll up or down to your mouse wheel using the maps above
2. Scroll up or down (whichever matches the binding you just set)
3. Move your mouse

**Comment by joelim-work** [comment] 2024-05-04 04:38
I couldn't reproduce this, most likely it's a bug in `tcell` (which appears to be fixed) where moving your mouse somehow triggers `WheelUp`/`WheelDown`.

Closing this issue but feel free to reopen if anyone else can still reproduce.

**Closed by joelim-work** 2024-05-04 04:38 UTC
