### ISSUE TITLE
lf does not update on live time

### ISSUE THREAD

**Issue by behradjafari1** [gokcehan/lf#325] opened 2020-04-09 18:37 UTC
I'm using lf on st terminal and sometimes when I move files or rename files after pressing the enter lf does not show the changes and show the old name or location and i have to close lf and reopen it, I never had this issue on ranger with st , is it something wrong with st or it's lf?

**Comment by shabahengam** [comment] 2020-04-09 18:55
duplicate of #213

**Comment by behradjafari1** [comment] 2020-04-09 20:01
I put "set period 1" in lfrc but still doesn't work!

**Comment by shabahengam** [comment] 2020-04-09 21:05
I can't reproduce the issue.which version of lf do you use?

**Comment by behradjafari1** [comment] 2020-04-09 21:32
I installed it from aur on archlinux I guess it should be the last version

**Comment by shabahengam** [comment] 2020-04-09 22:03
Does it happen on other terminal emulators like xterm or urxvt?

**Comment by behradjafari1** [comment] 2020-04-10 00:02
I found something, it works fine on fat32 and ext4 but not on exfat , i guess that's the problem or bug I don't know , ranger has that problem too on exfat

**Comment by gokcehan** [comment] 2020-04-13 16:20
@behradjafari1 We are using the modification time to decide if the file is changed or not. It may be the case the exfat may not be updating the modification times properly.

**Closed** 2020-07-08 02:17 UTC
Labels: question
