### ISSUE TITLE
bulkrenaming

### ISSUE THREAD

**Issue by siddhantdev** [gokcehan/lf#438] opened 2020-08-04 16:38 UTC
I am not very familiar with lf yet but I could not find any option for bulk renaming either in the documentation or the user guide. Is there an option for bulk renaming like in ranger? Is it gonna be added if it's not there?

**Comment by shabahengam** [comment] 2020-08-04 17:00
Duplicate of #149

**Comment by gokcehan** [comment] 2020-08-05 15:25
@siddhantdev I still think bulkrename should be left to custom commands or external tools.

Closing this in favor of the duplicate issue.

**Closed by gokcehan** 2020-08-05 15:25 UTC
