### ISSUE TITLE
%mv -i foo bar example from the tutorial not working

### ISSUE THREAD

**Issue by ngenisis** [gokcehan/lf#137] opened 2019-02-06 21:08 UTC
In the [tutorial](https://github.com/gokcehan/lf/wiki/Tutorial), there is an example where `%mv -i foo bar` prompts whether to overwrite `bar`. When I try this, I get the `mv: overwrite 'bat'?` output, but it doesn't allow me to enter any input. There is no `>` character at the beginning of the line like in the tutorial, maybe that is a clue. I know `shell-pipe` isn't completely broken since `%read a` allows me to enter input. I've tried this on Arch with termite and on Ubuntu 18.04 with the GNOME terminal.

**Comment by gokcehan** [comment] 2019-02-06 21:40
@ngenisis Thanks for reporting this. It seems that I have accidentally broken this while adding normal commands to cmap. I have pushed a commit to fix this. It should now work as intended.

It is unfortunate that r9 release has this bug. It may be nice to make a new release as soon as possible. Closing this issue now.

**Closed by gokcehan** 2019-02-06 21:40 UTC

**Comment by gokcehan** [comment] 2019-02-10 18:28
I have now released r10 which should not have this problem.
