### ISSUE TITLE
Custom delete command needs two "y" keystrokes

### ISSUE THREAD

**Issue by yanzhang0219** [gokcehan/lf#554] opened 2021-01-07 17:06 UTC
Hello,

First I put the info of my setup here:
* macOS version: Big Sur 11.1
* lf version: the lastest, built from the source.

I tested the custom `delete` command in the `lfrc` example. I need to press two `y` to delete a file. Is this expected?

The custom command and keybinding in the `lfrc`:
```
cmd delete ${{
  set -f
  printf "$fx\n"
  printf "delete?[y/N]"
  read ans
  [ $ans = "y" ] && rm -rf $fx
}}

map D delete
```

Then I create a new temp file by `touch temp` under my home folder for this testing. Next, I open lf and press `D` on this temp file. It goes back to the shell to ask me `y` or `N`, I press `y` followed by `Enter`. The cursor moves to the next line waiting for me to press another key. Next,
* if at this time I press `Enter`, it goes back to lf but the deletion fails. I quit lf, and I can see an error showing `--: line 6: [: =: unary operator expected`. I attached a short video below as a demo. 

https://user-images.githubusercontent.com/11582667/103921055-ddcedb00-50c6-11eb-8e5c-1e2671952c88.mov

* if at this time I press `y` again, it goes back to lf and the deletion successes. A short video attached below.

https://user-images.githubusercontent.com/11582667/103921266-24bcd080-50c7-11eb-8a2e-3d22b9d55638.mov

is this behavior (two keystrokes needed) expected?
Thank you very much.

**Comment by gokcehan** [comment] 2021-01-08 17:31
@yanzhang0219 The issue is likely related to #480 which I can't do much at the moment.

**Comment by yanzhang0219** [comment] 2021-01-08 17:39
Okay I see. Thank you. 
However, as a macOS user, this issue makes me discontinue using lf. I really love lf, and hope it could be solved soon.

**Comment by gokcehan** [comment] 2021-06-08 17:17
There has been multiple changes in regards to this and I'm not sure if we forgot to close this issue or the issue still persists. I'm closing this issue now. Feel free to reopen if the issue is reproducible with version r23.

**Closed by gokcehan** 2021-06-08 17:17 UTC
Labels: bug

**Comment by yanzhang0219** [comment] 2021-06-08 18:10
Thank you. I just now tested it and I confirm this bug is fixed. 👍
