### ISSUE TITLE
Strange line on the third column

### ISSUE THREAD

**Issue by dixiedream** [gokcehan/lf#1258] opened 2023-05-19 11:06 UTC
I've come up recently (LF version 29) with this behaviour which I believe is a bug or something related to my setup.

![pic-selected-230519-1300-51](https://github.com/gokcehan/lf/assets/7778930/6f6e7c19-99da-4f18-be37-19182bd9697d)

You see in the third column I've this underline under the first entry.

Terminal Emulator: Suckless terminal
Shell: ZSH
Display server: Xorg

**Comment by joelim-work** [comment] 2023-05-19 14:06
Version r29 adds a few new options to style the cursors in different columns, and the cursor for the preview column was changed to an underline by default. To get the old behaviour back, add `set cursorpreviewfmt "\033[7m"` to your config file.

**Comment by ilyagr** [comment] 2023-05-20 01:12
I think it's not too late to add it to the release notes as breaking change, is it (@gokcehan) ?. I could also add a section to https://github.com/gokcehan/lf/wiki/Tips with some screenshots.

I think people will get used to the change, especially if we document it better. I wish we could update the screencasts in https://github.com/gokcehan/lf/wiki/Tutorial, but that seems like a lot of work. I was actually looking into tools that make scripted terminal sessions for other reasons, but I haven't found a perfect one; I might try it again.

I'm resistant to changing the default because I feel like most people who would benefit from this feature (that is, they are less often confused about where their cursor is) would never learn of its existence if it was invisible by default. I do know that at least some people benefit from this: https://github.com/gokcehan/lf/issues/1102, https://github.com/gokcehan/lf/issues/1038#issuecomment-1366036069.

The second-best option for the default that I'm aware of (and that's still different from the main cursor) would be to use the dimmed attribute, as suggested in https://github.com/gokcehan/lf/issues/1038#issuecomment-1366364695. The problem is that it looks broken or invisible on many terminals.

---------------------------------------

All of this said, if this default continues to feel bothersome to @joelim-work and @gokcehan, I'll trust your judgement.

**Comment by ilyagr** [comment] 2023-05-20 02:21
I added a section in https://github.com/gokcehan/lf/wiki/Tips#changing-the-preview-directory-cursor.

**Comment by joelim-work** [comment] 2023-05-20 04:42
There are users that appreciate new changes, and then there are users that dread upgrading because of them.

That being said, I think this change is relatively minor (it is purely cosmetic and the old behaviour can be restored by setting a config file option), and my only suggestion is that we could have communicated this change more clearly.

Perhaps we could also [pin](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) this issue so that it is more visible.

**Comment by gokcehan** [comment] 2023-05-20 22:44
I have changed the release notes accordingly with some additional explanation. I will also keep this issue pinned for a while.

**Comment by ilyagr** [comment] 2023-05-20 23:15
Thank you very much!

**Comment by joelim-work** [comment] 2023-09-17 22:59
Closing as this is not an issue and can be fixed by configuration.

**Closed by joelim-work** 2023-09-17 22:59 UTC
